/* Private original-image uploads, including animated GIFs. */
const CHAT_MEDIA={drafts:{},urls:new Map(),sequence:0};
const CHAT_MEDIA_TYPES={png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',webp:'image/webp'};
function chatMediaReset(){CHAT_MEDIA.sequence++;for(const d of Object.values(CHAT_MEDIA.drafts))URL.revokeObjectURL(d.preview);CHAT_MEDIA.drafts={};CHAT_MEDIA.urls.clear();}
function chatMediaParse(body){try{if(!body.startsWith('VIVID_MEDIA:'))return null;const m=JSON.parse(body.slice(12));return typeof m.path==='string'&&/^[a-z0-9_]+\/(general|deals|resources)\/[0-9a-f-]{36}\/[0-9a-f-]{36}\.(png|jpg|jpeg|gif|webp)$/.test(m.path)&&typeof m.name==='string'&&m.name.length<=255&&typeof m.caption==='string'?m:null;}catch{return null;}}
function chatMediaHtml(m){const media=chatMediaParse(m.body||'');return media?'<div class="chat-media"><a target="_blank" rel="noopener noreferrer" aria-label="Open attached image"><img data-chat-media="'+esc(media.path)+'" alt="'+esc(media.name)+'" loading="lazy"></a><small>Loading image…</small></div>'+(media.caption?'<div class="chat-message-text">'+esc(media.caption)+'</div>':''):null;}
async function hydrateChatMedia(){const owner=CHAT.owner,epoch=CHAT.epoch;for(const img of qa('[data-chat-media]')){try{const path=img.dataset.chatMedia;let cached=CHAT_MEDIA.urls.get(path);if(!cached||cached.until<Date.now()){await syncSbSession();if(owner!==CHAT.owner||epoch!==CHAT.epoch)return;const {data,error}=await SB.storage.from('chat-media').createSignedUrl(path,3600);if(error)throw error;cached={url:data.signedUrl,until:Date.now()+3000000};CHAT_MEDIA.urls.set(path,cached);}if(!img.isConnected||owner!==CHAT.owner||epoch!==CHAT.epoch)return;const url=new URL(cached.url);if(url.protocol!=='https:')throw Error('Invalid image URL');img.parentElement.href=url.href;img.onload=()=>{if(img.isConnected)img.parentElement.nextElementSibling.textContent='';};img.onerror=()=>{CHAT_MEDIA.urls.delete(path);if(img.isConnected)img.parentElement.nextElementSibling.textContent='Image unavailable. Refresh chat to retry.';};img.src=url.href;}catch{if(img.isConnected)img.parentElement.nextElementSibling.textContent='Image unavailable. Refresh chat to retry.';}}}
function paintChatMediaDraft(){const box=q('#chatMediaDraft');if(!box)return;const d=CHAT_MEDIA.drafts[chatKey()];box.hidden=!d;box.innerHTML=d?'<img src="'+esc(d.preview)+'" alt="Attachment preview"><span>'+esc(d.file.name)+'</span><button type="button" id="chatMediaRemove" aria-label="Remove attachment">×</button>':'';if(d)q('#chatMediaRemove').onclick=()=>{if(CHAT.sending)return;URL.revokeObjectURL(d.preview);delete CHAT_MEDIA.drafts[chatKey()];paintChatMediaDraft();};}
async function chatMediaValidate(file){const ext=file?.name.split('.').pop().toLowerCase(),mime=CHAT_MEDIA_TYPES[ext];if(!mime||!file.size||file.size>10485760)throw Error('Choose a JPG, PNG, WebP, or GIF up to 10 MB.');const b=new Uint8Array(await file.slice(0,12).arrayBuffer()),s=String.fromCharCode(...b);if(!(mime==='image/png'&&b[0]===137&&s.slice(1,4)==='PNG'||mime==='image/jpeg'&&b[0]===255&&b[1]===216||mime==='image/gif'&&/^GIF8[79]a/.test(s)||mime==='image/webp'&&s.startsWith('RIFF')&&s.slice(8)==='WEBP'))throw Error('This file is not a supported image.');return {ext,mime};}
function bindChatMedia(){paintChatMediaDraft();hydrateChatMedia();q('#chatAttach').onclick=()=>{if(!CHAT.sending)q('#chatMediaFile').click();};q('#chatMediaFile').onchange=async e=>{const file=e.target.files[0],key=chatKey(),owner=CHAT.owner,seq=++CHAT_MEDIA.sequence;e.target.value='';if(!file)return;try{const type=await chatMediaValidate(file);if(owner!==CHAT.owner||key!==chatKey()||seq!==CHAT_MEDIA.sequence)return;const old=CHAT_MEDIA.drafts[key];if(old)URL.revokeObjectURL(old.preview);CHAT_MEDIA.drafts[key]={file,...type,id:crypto.randomUUID(),preview:URL.createObjectURL(file)};paintChatMediaDraft();q('#chatSendStatus').textContent='';}catch(e){if(owner===CHAT.owner&&key===chatKey())q('#chatSendStatus').textContent=e.message;}};}
async function chatMediaPrepare(d,caption,division,room,owner,epoch){if(!d)return caption;if(caption.length>3000)throw Error('Keep image captions under 3,000 characters.');await syncSbSession();if(owner!==CHAT.owner||epoch!==CHAT.epoch)throw Error('Chat changed. Return to your draft to send it.');if(!d.path){const path=division+'/'+room+'/'+owner+'/'+d.id+'.'+d.ext;const {error}=await SB.storage.from('chat-media').upload(path,d.file,{contentType:d.mime,upsert:false});if(error)throw error;d.path=path;}if(owner!==CHAT.owner||epoch!==CHAT.epoch)throw Error('Chat changed. Return to your draft to send it.');const body='VIVID_MEDIA:'+JSON.stringify({path:d.path,name:d.file.name.slice(0,255),caption});if(body.length>4000)throw Error('Shorten the caption to 3,000 characters or less.');return body;}
function chatMediaSent(key,d){if(d&&CHAT_MEDIA.drafts[key]===d){URL.revokeObjectURL(d.preview);delete CHAT_MEDIA.drafts[key];paintChatMediaDraft();}}
