/* Aggregate dashboard: no lead records are downloaded to draw charts. */
let dashboardData=null,dashboardDays=30,dashboardDivision=null,dashboardError='',dashboardRequest=0,dashboardOwner=null;
function resetDashboard(){dashboardRequest++;dashboardData=null;dashboardDivision=null;dashboardError='';dashboardOwner=null;}
async function loadDashboard(){
 if(dashboardOwner!==S.profile?.id){resetDashboard();dashboardOwner=S.profile?.id;}
 const request=++dashboardRequest;
 const division=dashboardDivision||(S.profile?.is_super_admin?'all':S.profile?.division);
 dashboardDivision=division;dashboardError='';
 try{const data=await api('/rest/v1/rpc/dashboard_overview',{method:'POST',body:{p_division:division,p_days:dashboardDays}});if(request===dashboardRequest)dashboardData=data;}
 catch(e){if(request===dashboardRequest){dashboardData=null;dashboardError=e.message||'Dashboard could not load';}}
}
function dashboardIcon(kind){const paths={leads:'M7 3h7l4 4v14H5V3h2m9 0v6h6M8 13h7M8 17h7',people:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M20 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75',check:'m6 12 4 4 8-8',chart:'M4 20V10m8 10V4m8 16v-8'};return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+(paths[kind]||paths.leads)+'"/></svg>';}
function dashboardTrend(rows){
 if(!rows?.length)return '<div class="empty">No trend data available.</div>';
 const max=Math.max(1,...rows.map(r=>Number(r.count)||0)),w=620,h=170;
 const points=rows.map((r,i)=>[48+i*(w-65)/Math.max(1,rows.length-1),h-20-(Number(r.count)||0)/max*(h-40)]);
 const line=points.map(p=>p.join(',')).join(' '),area='48,'+(h-20)+' '+line+' '+(w-17)+','+(h-20);
 const ticks=[0,.5,1].map(f=>{const y=h-20-f*(h-40);return '<line x1="48" y1="'+y+'" x2="603" y2="'+y+'" stroke="#e8eef6"/><text x="38" y="'+(y+4)+'" text-anchor="end">'+Math.round(max*f).toLocaleString()+'</text>';}).join('');
 const labels=[0,Math.floor((rows.length-1)/2),rows.length-1].map(i=>'<text x="'+points[i][0]+'" y="169" text-anchor="'+(i===0?'start':i===rows.length-1?'end':'middle')+'">'+esc(rows[i].day.slice(5))+'</text>').join('');
 return '<svg class="dash-trend" viewBox="0 0 620 180" role="img" aria-label="Leads added in the last '+dashboardDays+' days: '+rows.reduce((n,r)=>n+Number(r.count),0).toLocaleString()+' total">'+ticks+'<polygon points="'+area+'" fill="#2457e610"/><polyline points="'+line+'" fill="none" stroke="#2457e6" stroke-width="3"/>'+points.map((p,i)=>'<circle cx="'+p[0]+'" cy="'+p[1]+'" r="3" fill="#2457e6"><title>'+esc(rows[i].day)+': '+Number(rows[i].count).toLocaleString()+' leads</title></circle>').join('')+labels+'</svg><details class="dash-data"><summary>View daily counts</summary><div class="dash-counts">'+rows.map(r=>'<span>'+esc(r.day)+' <strong>'+Number(r.count).toLocaleString()+'</strong></span>').join('')+'</div></details>';
}
function dash(){
 const d=dashboardData,master=S.profile?.is_super_admin,division=dashboardDivision||(master?'all':S.profile?.division);
 const chooser=master?'<label class="sr-only" for="dashboardDivision">Dashboard division</label><select id="dashboardDivision">'+[['all','All divisions'],['vivid_life','Vivid Life'],['owner','Master'],['legacy_life','Legacy Life']].map(([v,l])=>'<option value="'+v+'" '+(v===division?'selected':'')+'>'+l+'</option>').join('')+'</select>':'<span class="badge">'+esc(divisionLabel(division))+'</span>';
 const uploadAllowed=division!=='all'?canAddLeads(division):canAddLeads(master?'vivid_life':division);
 const header='<div class="head dash-head"><div><h1>Dashboard</h1><p>Your leads, team, and production at a glance.</p></div><div class="dash-tools">'+chooser+'<label class="sr-only" for="dashboardDays">Sales and trend period</label><select id="dashboardDays">'+[7,30,90].map(n=>'<option value="'+n+'" '+(n===dashboardDays?'selected':'')+'>Last '+n+' days</option>').join('')+'</select><button class="btn primary" id="dashboardUpload" '+(uploadAllowed?'':'disabled title="Master can upload only to Vivid Life or Master"')+'>Upload leads</button><button class="btn secondary" data-dashboard-go="leads">Assign leads</button></div></div>';
 if(!d)return header+'<div class="card empty" role="status">'+esc(dashboardError||'Loading dashboard…')+' <button class="btn secondary" id="dashboardRetry">Retry</button></div>';
 const st=d.inventory||{},num=n=>Number(n||0).toLocaleString(),period='Last '+d.days+' days';
 const cards=[['Total leads',num(st.total_leads),'leads','Current inventory'],['Available',num(st.unassigned),'people','Current inventory'],['Assigned',num(st.assigned),'people','Current inventory'],['Closed',num(st.closed),'check','Current inventory'],['Monthly premium',money(d.monthly_premium),'chart','Sales recorded · '+period],['Annual premium',money(d.annual_premium),'chart','Sales recorded · '+period]];
 const total=Number(st.total_leads)||0,a=total?Number(st.unassigned)/total*100:0,b=total?Number(st.assigned)/total*100:0;
 const ring='<div class="dash-ring" style="background:conic-gradient(#2457e6 0 '+a+'%,#71a8ff '+a+'% '+(a+b)+'%,#16a36f '+(a+b)+'% 100%)" role="img" aria-label="'+num(st.unassigned)+' available, '+num(st.assigned)+' assigned, '+num(st.closed)+' closed"><div><strong>'+num(total)+'</strong><span>Total leads</span></div></div>';
 const legend=[['Available',st.unassigned,'#2457e6'],['Assigned',st.assigned,'#71a8ff'],['Closed',st.closed,'#16a36f']].map(([label,n,color])=>'<div><span><i style="background:'+color+'"></i>'+label+'</span><strong>'+num(n)+'</strong><small>'+(!total?'0':Number(n)>0&&Number(n)/total*100<1?'&lt;1':Math.round(Number(n)/total*100))+'%</small></div>').join('');
 const rows=(d.leaderboard||[]).slice(0,10).map((r,i)=>'<tr><td class="dash-rank">'+(i+1)+'</td><td><strong>'+esc(r.full_name||'Unnamed agent')+'</strong><span class="dash-agent-sub">'+(division==='all'?esc(divisionLabel(r.division))+' · ':'')+(r.archived?'Archived':r.active?'Active':'Inactive')+'</span></td><td>'+num(r.assigned)+'</td><td>'+num(r.closed_count)+'</td><td>'+money(r.monthly_premium)+'</td></tr>').join('');
 const activity=(S.audit||[]).slice(0,4).map(x=>'<div class="dash-activity-row"><span class="dash-activity-icon">'+dashboardIcon('leads')+'</span><div><strong>'+esc(String(x.action||'Activity').replace(/_/g,' '))+'</strong><small>'+esc(x.entity_type||'')+'</small></div><time>'+esc(new Date(x.created_at).toLocaleDateString())+'</time></div>').join('');
 return '<div class="dashboard">'+header+'<div class="dash-metrics">'+cards.map(([label,value,icon,hint])=>'<section class="card dash-metric"><span class="dash-icon">'+dashboardIcon(icon)+'</span><div><span class="dash-label">'+label+'</span><strong>'+value+'</strong><small>'+hint+'</small></div></section>').join('')+'</div><div class="dash-upper"><section class="card dash-panel"><div class="dash-panel-head"><h2>Leads added</h2><span class="muted small">'+period+' · UTC</span></div>'+dashboardTrend(d.trend)+'<p class="dash-footnote">Based on creation dates of leads still in this division.</p></section><section class="card dash-panel"><div class="dash-panel-head"><h2>Lead status</h2><span class="muted small">Current inventory</span></div><div class="dash-status">'+(total?ring:'<div class="dash-ring dash-ring-empty"><div><strong>0</strong><span>Total leads</span></div></div>')+'<div class="dash-legend">'+legend+'</div></div></section></div><div class="dash-lower"><section class="card dash-panel"><div class="dash-panel-head"><h2>Agent leaderboard</h2><button class="dash-link" data-dashboard-go="agents">View agents →</button></div><p class="dash-footnote">Ranked by closed sales, then monthly premium · '+period+'. Assigned counts are current.</p><div class="dash-leader-table"><table><thead><tr><th>#</th><th>Agent</th><th>Assigned</th><th>Closed sales</th><th>Monthly premium</th></tr></thead><tbody>'+(rows||'<tr><td colspan="5" class="empty">No agents in this division yet.</td></tr>')+'</tbody></table></div></section><aside class="dash-aside"><section class="dash-snapshot"><h2>Team snapshot</h2><div><span><strong>'+num(d.active_agents)+'</strong>Active agents</span><span><strong>'+num(d.closed_period)+'</strong>Sales · '+period+'</span><span><strong>'+num(st.assigned)+'</strong>Assigned leads</span></div></section><section class="card dash-panel"><div class="dash-panel-head"><h2>Recent activity</h2><button class="dash-link" data-dashboard-go="activity">View all →</button></div><p class="dash-footnote">'+(master?'Across your permitted divisions':'Your recent account actions')+'</p>'+(activity||'<p class="empty">No recent activity.</p>')+'</section></aside></div></div>';
}
function bindDashboard(){
 const reloadDashboard=async()=>{dashboardData=null;render();await loadDashboard();if(S.tab==='dashboard')render();};
 if(q('#dashboardDivision'))q('#dashboardDivision').onchange=e=>{dashboardDivision=e.target.value;reloadDashboard();};
 if(q('#dashboardDays'))q('#dashboardDays').onchange=e=>{dashboardDays=Number(e.target.value);reloadDashboard();};
 if(q('#dashboardRetry'))q('#dashboardRetry').onclick=reloadDashboard;
 async function go(tab,upload=false){try{S.divisionFilter=dashboardDivision==='all'?(S.profile.is_super_admin?'vivid_life':S.profile.division):dashboardDivision;S.tab=tab;S.selected.clear();S.filter='';S.leadTypeFilter='';S.stateFilter='';S.poolPage=1;await refreshLeadFilterCounts();await loadTabData();render();if(upload)importCsvModal();}catch(e){flash(e.message,true);}}
 qa('[data-dashboard-go]').forEach(b=>b.onclick=()=>go(b.dataset.dashboardGo));
 if(q('#dashboardUpload'))q('#dashboardUpload').onclick=()=>go('leads',true);
}
