'use strict';
let agencyScripts=[],callerName='',selectedOutcomeCaption=null,historyOffset=0,historyLoading=false,sessionFinished=0,sessionAnswered=0,sessionSeconds=0;
function clock(seconds){const s=Math.max(0,Math.floor(Number(seconds)||0));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');}
recordSessionCall=function(needsOutcome){if(!needsOutcome)return;sessionFinished++;if(callStartedAt){sessionAnswered++;sessionSeconds+=Math.max(0,Math.floor((Date.now()-callStartedAt)/1000));}$('sessioncalls').textContent=sessionFinished;$('sessionconnected').textContent=sessionAnswered;$('sessiontalk').textContent=sessionSeconds>=60?Math.floor(sessionSeconds/60)+'m '+sessionSeconds%60+'s':sessionSeconds+'s';};
window.updateDialerDisplay=function(){const locked=busy||callStarting||!!activeCall;document.querySelectorAll('[data-outcome]').forEach(b=>{b.disabled=locked||!current;b.setAttribute('aria-pressed',String(b.dataset.outcome===$('outcome').value&&b.dataset.caption===selectedOutcomeCaption));});$('togglekeypad').disabled=!activeCall||activeCall.status()!=='open';$('skipnext').disabled=locked||pendingOutcome||!current;const list=visible(),i=current?list.findIndex(l=>l.id===current.id):-1,next=i>=0?list[i+1]:null;$('nextleadname').textContent=next?[next.first_name,next.last_name].filter(Boolean).join(' ')||'Unnamed lead':'End of this queue';$('nextleadphone').textContent=next?.phone||'';$('skipnext').disabled=$('skipnext').disabled||!next;$('calllead').hidden=$('startqueue').hidden=!!activeCall||callStarting;$('notesRight').disabled=busy||!current;};
window.updateDialerLead=function(l){document.querySelectorAll('.leadline').forEach(row=>row.classList.toggle('is-current',row.dataset.leadId===l.id));$('folderfact').textContent=l.lead_type||'Unlabeled';$('notesRight').value=l.call_notes||'';selectedOutcomeCaption=l.agent_status==='appointment_follow_up'?'Appointment':l.agent_status==='call_back'?'Call Back':l.agent_status==='not_interested'?'Not Interested':l.agent_status==='dead_number'?'Dead Number':null;const matched=agencyScripts.find(s=>s.lead_type&&String(s.lead_type).toLowerCase()===String(l.lead_type||'').toLowerCase());if(matched)$('scriptselect').value=matched.id;renderScript();};
document.querySelectorAll('[data-outcome]').forEach(b=>{b.setAttribute('aria-pressed','false');b.onclick=()=>{if(!current||busy||activeCall||callStarting)return;selectedOutcomeCaption=b.dataset.caption;$('outcome').value=b.dataset.outcome;controls();};});
$('notes').addEventListener('input',()=>{$('notesRight').value=$('notes').value;});$('notesRight').addEventListener('input',()=>{$('notes').value=$('notesRight').value;});
for(const id of ['leadsearch','globalSearch'])$(id).addEventListener('input',()=>{const value=$(id).value;$('leadsearch').value=$('globalSearch').value=value;render();});
$('togglekeypad').onclick=()=>{const open=$('togglekeypad').getAttribute('aria-expanded')!=='true';$('togglekeypad').setAttribute('aria-expanded',String(open));controls();};
$('skipnext').onclick=()=>{if(!allowChange())return;const list=visible(),i=list.findIndex(l=>l.id===current?.id);if(i>=0&&list[i+1])show(list[i+1]);};
function rightTab(notes){$('scriptReader').hidden=notes;$('rightNotes').hidden=!notes;$('scriptTab').classList.toggle('active',!notes);$('rightNotesTab').classList.toggle('active',notes);if(notes&&current)$('notesRight').focus();}
$('scriptTab').onclick=()=>rightTab(false);$('rightNotesTab').onclick=()=>rightTab(true);
function renderScript(){const s=agencyScripts.find(s=>s.id===$('scriptselect').value);$('scripttitle').textContent=s?.title||'Agency call script';$('scriptbody').textContent=s?String(s.body||'').replace(/\{\{\s*(Your Name|Agent Name)\s*\}\}/gi,callerName).replace(/\{\{\s*First Name\s*\}\}/gi,current?.first_name||'the client'):'No saved scripts are available. Add one in the portal’s Sales scripts area.';}
$('scriptselect').onchange=renderScript;
async function loadDisplayProfile(){try{const d=await api({action:'profile'});callerName=d.profile?.full_name||'Your account';$('profilename').textContent=callerName;$('profileinitials').textContent=callerName.split(/\s+/).slice(0,2).map(n=>n[0]).join('').toUpperCase();$('profileagency').textContent=String(d.profile?.division||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())||'Agent portal';agencyScripts=d.scripts||[];const select=$('scriptselect');select.replaceChildren();if(!agencyScripts.length){const o=document.createElement('option');o.textContent='No agency scripts yet';select.append(o);}for(const s of agencyScripts){const o=document.createElement('option');o.value=s.id;o.textContent=s.title+(s.lead_type?' · '+s.lead_type:'');select.append(o);}renderScript();}catch(e){$('scriptbody').textContent=e.message;}}
async function loadCallHistory(){if(historyLoading)return;historyLoading=true;$('refreshhistory').disabled=true;$('historymessage').textContent='Loading your calls…';try{const d=await api({action:'history',offset:historyOffset});const calls=d.calls||[],body=$('historyrows');body.replaceChildren();for(const c of calls){const tr=document.createElement('tr');const status=c.finished?(c.call_status||'Ended'):'Confirming call duration';for(const value of [new Date(c.created_at).toLocaleString(),c.phone,status,clock(c.duration_seconds),String(c.used_minutes)]){const td=document.createElement('td');td.textContent=value;tr.append(td);}body.append(tr);}$('historymessage').textContent=calls.length?'Showing your '+calls.length+' most recent calls on this page.':'No calls on this page yet.';$('historyprevious').disabled=historyOffset===0;$('historynext').disabled=calls.length<50;}catch(e){$('historymessage').textContent=e.message;}finally{historyLoading=false;$('refreshhistory').disabled=false;}}
function displayView(name){if(!['workspace','history','billing'].includes(name))return;if(name!=='workspace'&&(activeCall||callStarting)){message('Finish this call before changing dialer tabs.',true);return;}for(const view of ['workspace','history','billing'])$(view).hidden=view!==name;document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===name);b.setAttribute('aria-selected',String(b.dataset.view===name));});if(name==='history')loadCallHistory();if(name==='billing')refreshUsage();}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>displayView(b.dataset.view));$('refreshhistory').onclick=loadCallHistory;$('historyprevious').onclick=()=>{if(!historyLoading){historyOffset=Math.max(0,historyOffset-50);loadCallHistory();}};$('historynext').onclick=()=>{if(!historyLoading){historyOffset+=50;loadCallHistory();}};
window.addEventListener('storage',e=>{if(e.key==='lld_session'&&session()?.user?.id!==accountOwner){agencyScripts=[];callerName='';$('scriptbody').textContent='Account changed. Reload the page.';$('historyrows').replaceChildren();$('profilename').textContent='Account changed';}});
controls();if(session()?.access_token){loadDisplayProfile();$('load').click();}else message('Sign in to the portal and complete two-step verification first.',true);
