function canSendAcrossAgencies(){return S.profile?.role==='admin'&&(S.profile.is_super_admin||S.profile.id==='4733ed70-f774-4209-a8b5-fd233d0bb638');}
function leadSendDestinations(){return (S.divisions||[]).filter(d=>S.profile?.is_super_admin||(d.id!=='legacy_life'&&adminDivisionList().includes(d.id)));}
/* Names come from the scoped registry; creation is enforced by a Master-only RPC. */
async function loadDivisionRegistry(){S.divisions=await api('/rest/v1/divisions?select=id,name,is_system&order=created_at,name')||[];}
async function loadDivisionDirectory(){if(!S.profile?.is_super_admin)throw Error('Master Admin only');S.divisionDirectory=await api('/rest/v1/rpc/division_admin_directory',{method:'POST',body:{}})||[];}
function divisionsPage(){if(!S.profile?.is_super_admin)return '<p class="error">Master Admin only.</p>';return '<div class="head"><div><h1>Agencies</h1><p>Create separate workspaces for your agencies. Each agency has its own agents, lead pool, scripts, and chat.</p></div><button id="addDivision" class="btn primary">Add agency</button></div><div class="division-grid">'+(S.divisionDirectory||[]).map(d=>'<section class="card division-card"><div class="head"><h2>'+esc(d.name)+'</h2><span class="badge">'+(d.is_system?'Existing agency':'Agency')+'</span></div><p class="muted small">Agency admins</p><div class="division-admins">'+(d.admins.length?d.admins.map(a=>'<div><strong>'+esc(a.name)+'</strong>'+(a.active?'':' <span class="badge red">Disabled</span>')+'</div>').join(''):'<p class="muted">No agency admin assigned yet.</p>')+'</div><p class="muted small">Your Master account retains oversight.</p><div class="row"><button class="btn secondary" data-division-open="'+esc(d.id)+'">Open agents</button>'+(d.id!=='owner'?'<button class="btn primary" data-division-admin="'+esc(d.id)+'">Add admin</button>':'')+'</div></section>').join('')+'</div>';}
function bindDivisions(){bindDivisionRecipients();if(S.tab!=='divisions'||!S.profile?.is_super_admin)return;q('#addDivision').onclick=addDivisionModal;qa('[data-division-open]').forEach(b=>b.onclick=async()=>{S.divisionFilter=b.dataset.divisionOpen;S.tab='agents';await loadCore();render();});qa('[data-division-admin]').forEach(b=>b.onclick=()=>addAdminModal(b.dataset.divisionAdmin));}
function addDivisionModal(){if(!S.profile?.is_super_admin)return;modal('<h2>Add agency</h2><form id="divisionForm" class="stack"><div class="field"><label for="divisionName">Agency name</label><input id="divisionName" name="name" required minlength="2" maxlength="80" placeholder="e.g. Summit Life" autofocus></div><div class="field"><label for="divisionAdmin">Existing admin (optional)</label><select id="divisionAdmin"><option value="">Assign an admin later</option>'+S.admins.filter(a=>a.active&&!a.is_super_admin).map(a=>'<option value="'+esc(a.id)+'">'+esc(a.full_name)+'</option>').join('')+'</select></div><p class="muted small">Selecting an existing admin adds access to this new agency. Their current agency access stays in place. You can also create a new admin after saving.</p><div id="divisionError" role="alert"></div><div class="row"><button id="divisionCancel" type="button" class="btn secondary">Cancel</button><button id="divisionSave" class="btn primary">Create agency</button></div></form>');q('#divisionCancel').onclick=closeModal;q('#divisionForm').onsubmit=async e=>{e.preventDefault();const button=q('#divisionSave');button.disabled=true;try{const created=await api('/rest/v1/rpc/create_division',{method:'POST',body:{p_name:q('#divisionName').value.trim(),p_admin_id:q('#divisionAdmin').value||null}});closeModal();S.tab='divisions';await loadCore();S.msg=created.name+' created. Add an admin or open its agents to get started.';render();}catch(e){const error=q('#divisionError');if(error){error.className='error';error.textContent=e.message;}else flash(e.message,true);}finally{if(button.isConnected)button.disabled=false;}};}

function destinationAgents(division){return (S.agents||[]).filter(a=>a.active&&!a.archived&&a.division===division);}
function destinationRecipientOptions(division){return '<option value="">Agency lead pool</option>'+destinationAgents(division).map(a=>'<option value="'+esc(a.id)+'" '+(S.sendRecipient===a.id?'selected':'')+'>'+esc(a.full_name)+'</option>').join('');}
function masterSendControls(){if(!canSendAcrossAgencies())return '';const source=operatingDivision();if(source==='legacy_life')return '<span class="notice">Legacy leads stay in Legacy. Choose a Legacy agent to assign them.</span>';if(S.sendSource!==source){S.sendSource=source;S.sendDestination='';S.sendRecipient='';}if(!leadSendDestinations().some(d=>d.id===S.sendDestination)){S.sendDestination='';S.sendRecipient='';}if(!destinationAgents(S.sendDestination).some(a=>a.id===S.sendRecipient))S.sendRecipient='';return '<select id="sendDivisionPick" aria-label="Destination agency"><option value="">Send to agency…</option>'+leadSendDestinations().map(d=>'<option value="'+esc(d.id)+'" '+(d.id===S.sendDestination?'selected':'')+'>'+esc(d.name)+'</option>').join('')+'</select><select id="sendRecipientPick" aria-label="Recipient in destination agency" '+(S.sendDestination?'':'disabled')+'>'+destinationRecipientOptions(S.sendDestination)+'</select><button id="sendDivision" class="btn primary" '+(S.selected.size?'':'disabled')+'>Send selected ('+S.selected.size+')</button>';}
function bindDivisionRecipients(){const division=q('#sendDivisionPick'),recipient=q('#sendRecipientPick');if(!division||!recipient)return;division.onchange=()=>{S.sendDestination=division.value;S.sendRecipient='';recipient.innerHTML=destinationRecipientOptions(division.value);recipient.disabled=!division.value;};recipient.onchange=()=>{S.sendRecipient=recipient.value;};}
async function sendSelectedToDivision(){const destination=q('#sendDivisionPick')?.value,agent=q('#sendRecipientPick')?.value||null,source=operatingDivision(),ids=[...S.selected];if(!canSendAcrossAgencies())return;if(!leadSendDestinations().some(d=>d.id===destination))return flash('Choose an authorized destination agency.',true);if(!destination)return flash('Choose a destination agency.',true);if(!ids.length)return flash('Select at least one lead.',true);if(destination===source&&!agent)return flash('Choose an agent, or select a different agency pool.',true);const recipient=agent?destinationAgents(destination).find(a=>a.id===agent):null;if(agent&&!recipient)return flash('This agent is no longer available in that agency. Refresh and choose again.',true);const label=recipient?recipient.full_name+' in '+divisionLabel(destination):divisionLabel(destination)+' lead pool';if(!confirm('Send '+ids.length+' leads to '+label+'?'+(agent?' They will be assigned directly to this agent.':' They will move into that agency’s unassigned lead pool.')))return;const b=q('#sendDivision');b.disabled=true;try{const n=await api('/rest/v1/rpc/send_leads_to_recipient',{method:'POST',body:{p_lead_ids:ids,p_source:source,p_destination:destination,p_agent_id:agent}});S.selected.clear();await reload(Number(n)+' leads sent to '+label+'.')}catch(e){flash(e.message,true)}finally{if(b.isConnected)b.disabled=false}}

function masterAgentControls(agents){const admins=(S.adminRecipients||[]).filter(a=>a.divisions.includes(operatingDivision()));return '<select id="pick" aria-label="Agent or admin in selected agency"><option value="">Choose agent or admin…</option>'+agents.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.full_name)+'</option>').join('')+admins.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.full_name)+(x.id===S.profile.id?' — Yourself':'')+' (Admin)</option>').join('')+'</select><button id="assign" class="btn" '+(S.selected.size?'':'disabled')+'>Assign selected ('+S.selected.size+')</button><button id="assignSelf" class="btn primary" '+(S.selected.size?'':'disabled')+'>Assign to myself ('+S.selected.size+')</button>';}
