/* Names come from the scoped registry; creation is enforced by a Master-only RPC. */
async function loadDivisionRegistry(){S.divisions=await api('/rest/v1/divisions?select=id,name,is_system&order=created_at,name')||[];}
async function loadDivisionDirectory(){if(!S.profile?.is_super_admin)throw Error('Master Admin only');S.divisionDirectory=await api('/rest/v1/rpc/division_admin_directory',{method:'POST',body:{}})||[];}
function divisionsPage(){if(!S.profile?.is_super_admin)return '<p class="error">Master Admin only.</p>';return '<div class="head"><div><h1>Divisions</h1><p>Create separate workspaces for your agencies. Each division has its own agents, lead pool, scripts, and chat.</p></div><button id="addDivision" class="btn primary">Add division</button></div><div class="division-grid">'+(S.divisionDirectory||[]).map(d=>'<section class="card division-card"><div class="head"><h2>'+esc(d.name)+'</h2><span class="badge">'+(d.is_system?'Existing division':'Division')+'</span></div><p class="muted small">Division admins</p><div class="division-admins">'+(d.admins.length?d.admins.map(a=>'<div><strong>'+esc(a.name)+'</strong>'+(a.active?'':' <span class="badge red">Disabled</span>')+'</div>').join(''):'<p class="muted">No division admin assigned yet.</p>')+'</div><p class="muted small">Your Master account retains oversight.</p><div class="row"><button class="btn secondary" data-division-open="'+esc(d.id)+'">Open agents</button>'+(d.id!=='owner'?'<button class="btn primary" data-division-admin="'+esc(d.id)+'">Add admin</button>':'')+'</div></section>').join('')+'</div>';}
function bindDivisions(){if(S.tab!=='divisions'||!S.profile?.is_super_admin)return;q('#addDivision').onclick=addDivisionModal;qa('[data-division-open]').forEach(b=>b.onclick=async()=>{S.divisionFilter=b.dataset.divisionOpen;S.tab='agents';await loadCore();render();});qa('[data-division-admin]').forEach(b=>b.onclick=()=>addAdminModal(b.dataset.divisionAdmin));}
function addDivisionModal(){if(!S.profile?.is_super_admin)return;modal('<h2>Add division</h2><form id="divisionForm" class="stack"><div class="field"><label for="divisionName">Division name</label><input id="divisionName" name="name" required minlength="2" maxlength="80" placeholder="e.g. Summit Life" autofocus></div><div class="field"><label for="divisionAdmin">Existing admin (optional)</label><select id="divisionAdmin"><option value="">Assign an admin later</option>'+S.admins.filter(a=>a.active&&!a.is_super_admin).map(a=>'<option value="'+esc(a.id)+'">'+esc(a.full_name)+'</option>').join('')+'</select></div><p class="muted small">Selecting an existing admin adds access to this new division. Their current division access stays in place. You can also create a new admin after saving.</p><div id="divisionError" role="alert"></div><div class="row"><button id="divisionCancel" type="button" class="btn secondary">Cancel</button><button id="divisionSave" class="btn primary">Create division</button></div></form>');q('#divisionCancel').onclick=closeModal;q('#divisionForm').onsubmit=async e=>{e.preventDefault();const button=q('#divisionSave');button.disabled=true;try{const created=await api('/rest/v1/rpc/create_division',{method:'POST',body:{p_name:q('#divisionName').value.trim(),p_admin_id:q('#divisionAdmin').value||null}});closeModal();S.tab='divisions';await loadCore();S.msg=created.name+' created. Add an admin or open its agents to get started.';render();}catch(e){const error=q('#divisionError');if(error){error.className='error';error.textContent=e.message;}else flash(e.message,true);}finally{if(button.isConnected)button.disabled=false;}};}

function masterSendControls(){if(operatingDivision()==='legacy_life')return '<span class="notice">Legacy leads stay in Legacy. Its admins assign agents.</span>';return '<select id="sendDivisionPick" aria-label="Destination division"><option value="">Send to division…</option>'+(S.divisions||[]).filter(d=>d.id!==operatingDivision()).map(d=>'<option value="'+esc(d.id)+'">'+esc(d.name)+'</option>').join('')+'</select><button id="sendDivision" class="btn primary" '+(S.selected.size?'':'disabled')+'>Send selected ('+S.selected.size+')</button>';}
async function sendSelectedToDivision(){const destination=q('#sendDivisionPick')?.value,source=operatingDivision(),ids=[...S.selected];if(!S.profile?.is_super_admin)return;if(!destination)return flash('Choose a destination division.',true);if(!ids.length)return flash('Select at least one lead.',true);if(!confirm('Send '+ids.length+' leads to '+divisionLabel(destination)+'? They will move into that division’s unassigned lead pool.'))return;const b=q('#sendDivision');b.disabled=true;try{const n=await api('/rest/v1/rpc/send_leads_to_division',{method:'POST',body:{p_lead_ids:ids,p_source:source,p_destination:destination}});S.selected.clear();await reload(Number(n)+' leads sent to '+divisionLabel(destination)+'.')}catch(e){flash(e.message,true)}finally{b.disabled=false}}
