/* Division-scoped sales board. Realtime carries invalidations, never lead records. */
const LB={data:null,division:null,error:'',channel:null,timer:null,debounce:null,owner:null,epoch:0,request:0,connected:false,starting:false,newIds:new Set()};
function resetLeaderboard(){stopLeaderboard();LB.data=null;LB.division=null;LB.error='';LB.owner=null;LB.newIds.clear();}
function stopLeaderboard(){LB.epoch++;LB.request++;clearInterval(LB.timer);clearTimeout(LB.debounce);LB.timer=null;LB.debounce=null;LB.starting=false;LB.connected=false;if(LB.channel){SB.removeChannel(LB.channel);LB.channel=null;}document.removeEventListener('visibilitychange',leaderboardVisibility);window.removeEventListener('online',leaderboardVisibility);}
function leaderboardVisibility(){if(!document.hidden&&S.tab==='leaderboard')refreshLeaderboard();}
function leaderboardScope(){return LB.division||(S.profile?.role==='admin'&&S.profile?.is_super_admin?'all':S.profile?.division);}
async function loadLeaderboard(){if(LB.owner!==S.profile?.id){resetLeaderboard();LB.owner=S.profile?.id;}await refreshLeaderboard(false);}
async function refreshLeaderboard(paint=true){if(!S.profile?.active||S.tab!=='leaderboard')return;const request=++LB.request,owner=S.profile.id,division=leaderboardScope();try{const d=await api('/rest/v1/rpc/live_leaderboard',{method:'POST',body:{p_division:division}});if(request!==LB.request||owner!==S.profile?.id||S.tab!=='leaderboard')return;const previous=new Set((LB.data?.today_feed||[]).map(x=>x.id));LB.newIds=new Set(LB.data?(d.today_feed||[]).filter(x=>!previous.has(x.id)).map(x=>x.id):[]);LB.data=d;LB.error='';}catch(e){if(request!==LB.request)return;LB.error=e.message||'Unable to update leaderboard';LB.data=null;}if(paint)paintLeaderboard();}
function queueLeaderboardRefresh(){clearTimeout(LB.debounce);LB.debounce=setTimeout(()=>{if(!document.hidden)refreshLeaderboard();},200);}
function leaderboardLiveLabel(){return LB.error?'Update failed':LB.connected?'Live':'Reconnecting · auto-refresh on';}
function updateLeaderboardConnection(){const el=q('#leaderboardConnection');if(el){el.textContent=leaderboardLiveLabel();el.classList.toggle('connected',LB.connected&&!LB.error);}}
async function startLeaderboard(){if(S.tab!=='leaderboard'){if(LB.channel||LB.timer||LB.starting)stopLeaderboard();return;}if(LB.channel||LB.starting)return;LB.starting=true;const epoch=LB.epoch;LB.timer=setInterval(()=>{if(!document.hidden)refreshLeaderboard();},30000);document.addEventListener('visibilitychange',leaderboardVisibility);window.addEventListener('online',leaderboardVisibility);try{await SB.realtime.setAuth(S.session.access_token);if(epoch!==LB.epoch||S.tab!=='leaderboard')return;LB.channel=SB.channel('lld-leaderboard-'+S.profile.id).on('postgres_changes',{event:'UPDATE',schema:'public',table:'leaderboard_updates'},queueLeaderboardRefresh).subscribe(status=>{if(epoch!==LB.epoch)return;LB.connected=status==='SUBSCRIBED';updateLeaderboardConnection();if(LB.connected)queueLeaderboardRefresh();});}catch(e){LB.connected=false;updateLeaderboardConnection();}finally{if(epoch===LB.epoch)LB.starting=false;}}
function leaderboardPage(){return '<section id="leaderboardBoard" class="sales-board">'+leaderboardContent()+'</section>';}
function leaderboardContent(){const d=LB.data,t=d?.totals||{},rank=d?.rankings||[],feed=d?.today_feed||[],cash=v=>money(Number(v||0)),num=v=>Number(v||0).toLocaleString(),scope=leaderboardScope(),scopes=d?.scopes||(S.profile?.role==='admin'?adminDivisionList():[S.profile?.division]);const options=[...(scopes.length>1?[['all','All permitted divisions']]:[]),...scopes.map(v=>[v,divisionLabel(v)])];const header='<header class="sales-board-head"><div><span class="sales-eyebrow">LIFE LEAD DISTRIBUTION · SALES BOARD</span><h1>Leaderboard<span class="sales-live" id="leaderboardConnection" role="status">'+esc(leaderboardLiveLabel())+'</span></h1></div><div class="sales-board-tools">'+(options.length>1?'<select id="leaderboardDivision" aria-label="Leaderboard division">'+options.map(([v,l])=>'<option value="'+esc(v)+'" '+(v===scope?'selected':'')+'>'+esc(l)+'</option>').join('')+'</select>':'<span>'+esc(divisionLabel(scope))+'</span>')+'<button type="button" id="leaderboardRefresh">Refresh</button><button type="button" id="leaderboardFullscreen">Full screen</button></div></header>';
if(!d)return header+'<div class="sales-empty" role="status">'+esc(LB.error||'Loading live production…')+'</div>';
const metric=(label,value,hint)=>'<section class="sales-metric"><span>'+label+'</span><strong>'+value+'</strong><small>'+hint+'</small></section>';
return header+'<div class="sales-board-grid"><section class="sales-panel sales-rank"><div class="sales-panel-title"><h2>Month-to-date leaderboard</h2><span>ANNUAL PREMIUM</span></div><div class="sales-rank-head"><span>Agent</span><span>AP</span><span>Deals</span><span>Avg AP</span></div><ol>'+rank.map((r,i)=>'<li class="sales-rank-row rank-'+(i+1)+(r.agent_id===S.profile.id?' is-you':'')+'"><span class="sales-agent"><b class="sales-place">'+(i+1)+'</b><span>'+esc(r.agent_name)+(r.agent_id===S.profile.id?'<small>You</small>':'')+'</span></span><strong>'+cash(r.ap)+'</strong><span>'+num(r.deals)+'</span><span>'+cash(r.deals?r.ap/r.deals:0)+'</span></li>').join('')+'</ol>'+(rank.length?'':'<div class="sales-empty">Your team will appear here.</div>')+'</section><section class="sales-panel sales-today"><div class="sales-panel-title"><h2>Today’s deals</h2><span>'+num(t.today_deals)+' CLOSED</span></div><div class="sales-today-total">'+cash(t.today_ap)+'<small>Annual premium written today</small></div><div class="sales-feed">'+(feed.length?feed.map(r=>'<article class="sales-deal '+(LB.newIds.has(r.id)?'sales-deal-new':'')+'"><span class="sales-deal-icon" aria-hidden="true">✦</span><div><strong>'+esc(r.agent_name)+'</strong><span>'+esc(r.carrier)+' · '+esc(r.policy_type)+'</span><time datetime="'+esc(r.created_at)+'">'+esc(new Date(r.created_at).toLocaleTimeString('en-US',{timeZone:'America/Detroit',hour:'numeric',minute:'2-digit'}))+'</time></div><div class="sales-deal-value"><strong>'+cash(r.annual_premium)+'</strong><small>'+cash(r.monthly_premium)+' / mo</small></div></article>').join(''):'<div class="sales-empty"><span class="sales-empty-star">✦</span>No closes yet today.<small>The next deal appears here automatically.</small></div>')+'</div>'+(Number(t.today_deals)>50?'<p class="sales-footnote">Showing the latest 50 deals. Totals include every deal today.</p>':'')+'</section><aside class="sales-totals">'+metric('MONTH TO DATE',cash(t.month_ap),num(t.month_deals)+' closed deals')+metric('THIS WEEK',cash(t.week_ap),num(t.week_deals)+' closed deals · Monday–Sunday')+metric('MONTHLY PREMIUM',cash(t.month_mp),'From this month’s closed deals')+metric('ACTIVE PRODUCERS',num(t.active_producers),'Agents with a close this month')+metric('YEAR TO DATE',cash(t.year_ap),num(t.year_deals)+' closed deals')+'</aside></div><footer class="sales-board-footer"><span>AP = annualized premium · Based on when deals are recorded as closed · Detroit time</span><span>Updated '+esc(new Date(d.as_of).toLocaleTimeString('en-US',{timeZone:'America/Detroit',hour:'numeric',minute:'2-digit',second:'2-digit'}))+'</span></footer>';
}
function paintLeaderboard(){const board=q('#leaderboardBoard');if(!board||S.tab!=='leaderboard')return;const scroll=board.querySelector('.sales-feed')?.scrollTop||0;board.innerHTML=leaderboardContent();const feed=board.querySelector('.sales-feed');if(feed)feed.scrollTop=scroll;bindLeaderboard();}
function bindLeaderboard(){if(S.tab!=='leaderboard')return;const select=q('#leaderboardDivision');if(select)select.onchange=()=>{LB.division=select.value;LB.data=null;LB.error='';paintLeaderboard();refreshLeaderboard();};const refresh=q('#leaderboardRefresh');if(refresh)refresh.onclick=()=>refreshLeaderboard();const full=q('#leaderboardFullscreen');if(full)full.onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await q('#leaderboardBoard').requestFullscreen();}catch{full.textContent='Full screen unavailable';}};updateLeaderboardConnection();startLeaderboard();}
