function adminDivisionList(){return S.adminDivisions?.length?S.adminDivisions:S.profile?.is_super_admin?['owner','vivid_life','legacy_life']:S.profile?.role==='admin'?[S.profile.division]:[]}
function hasMultipleAdminDivisions(){return adminDivisionList().length>1}
function operatingDivision(){return S.profile?.role==='admin'&&adminDivisionList().includes(S.divisionFilter)?S.divisionFilter:S.profile?.division}
function adminDivisionOptions(selected){return adminDivisionList().map(d=>'<option value="'+d+'" '+(d===selected?'selected':'')+'>'+esc(divisionLabel(d))+'</option>').join('')}
function canManageTeam(agent){return !!(agent&&!agent.archived&&S.profile?.role==='admin'&&S.profile.active&&adminDivisionList().includes(agent.division));}
function teamSettingsModal(id){
 const agent=S.agents.find(a=>a.id===id);if(!canManageTeam(agent))return;
 const leaders=S.agents.filter(a=>a.id!==id&&a.is_team_leader&&a.active&&!a.archived&&a.division===agent.division);
 modal('<h2>Team settings: '+esc(agent.full_name)+'</h2><form id="teamForm" class="stack"><label><input id="isTeamLeader" type="checkbox" '+(agent.is_team_leader?'checked':'')+'> Team leader — may upload leads and delete only their own non-closed uploads</label><div class="field"><label>Assigned team leader</label><select id="teamLeader"><option value="">No team leader</option>'+leaders.map(a=>'<option value="'+a.id+'" '+(a.id===agent.team_leader_id?'selected':'')+'>'+esc(a.full_name)+'</option>').join('')+'</select></div><div class="notice">Team members and their leader must be in the same division. Division admins can manage their own division; the Master Admin can manage every division.</div><div id="teamError" role="status"></div><div class="row"><button type="button" class="btn secondary" id="cancel">Cancel</button><button class="btn primary">Save team settings</button></div></form>');
 const sync=()=>{q('#teamLeader').disabled=q('#isTeamLeader').checked;if(q('#isTeamLeader').checked)q('#teamLeader').value=''};q('#isTeamLeader').onchange=sync;sync();q('#cancel').onclick=closeModal;
 q('#teamForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{await api('/rest/v1/rpc/set_agent_team',{method:'POST',body:{p_agent:id,p_is_leader:q('#isTeamLeader').checked,p_leader:q('#teamLeader').value||null}});closeModal();await reload('Team settings saved.')}catch(x){q('#teamError').className='error';q('#teamError').textContent=x.message}finally{button.disabled=false}};
}
async function loadMyUploads(){
 const params=new URLSearchParams({select:'*',uploaded_by:'eq.'+S.profile.id,division:'eq.'+S.profile.division,order:'created_at.desc,id.desc',limit:String(S.pageSize),offset:String((S.uploadPage-1)*S.pageSize)});
 const result=await apiPage('/rest/v1/leads?'+params);S.uploads=result.data;S.uploadCount=result.count;
 if(S.uploadPage>pageCount(S.uploadCount)){S.uploadPage=pageCount(S.uploadCount);return loadMyUploads()}
}
function myUploads(){
 const rows=S.uploads||[];
 return '<div class="head"><div><h1>My uploads</h1><p>Leads you added to '+esc(divisionLabel(S.profile.division))+'. Your admin assigns them to agents.</p></div></div><div class="tools"><button id="teamAddLead" class="btn primary">Add lead</button><button id="teamImport" class="btn secondary">Import CSV</button><button id="teamDelete" class="btn danger">Delete selected uploads</button></div><div class="notice">You can delete only leads you uploaded. Closed business is protected. Older uploads without a verified uploader remain under admin control.</div>'+pager('uploads',S.uploadPage,S.uploadCount)+'<div class="table"><table><thead><tr><th>Select</th><th>Name</th><th>Phone</th><th>Lead type / batch</th><th>Status</th><th>Source file</th></tr></thead><tbody>'+(rows.length?rows.map(l=>'<tr><td><input class="teamUploadCheck" type="checkbox" value="'+l.id+'" '+(l.status==='closed'?'disabled':'')+'></td><td>'+esc((l.first_name||'')+' '+(l.last_name||''))+'</td><td>'+esc(l.phone)+'</td><td>'+esc(l.lead_type??'Unlabeled')+'</td><td>'+esc(l.status)+'</td><td>'+esc(l.csv_filename)+'</td></tr>').join(''):'<tr><td colspan="6" class="empty">No uploads yet.</td></tr>')+'</tbody></table></div>'+pager('uploads',S.uploadPage,S.uploadCount);
}
function bindMyUploads(){
 q('#teamAddLead').onclick=addLeadModal;q('#teamImport').onclick=importCsvModal;
 q('#teamDelete').onclick=async()=>{const ids=qa('.teamUploadCheck:checked').map(x=>x.value);if(!ids.length)return flash('Select the uploads you want to delete.',true);if(!confirm('Permanently delete '+ids.length+' of your uploaded leads? This also removes any open assignments for those leads.'))return;const button=q('#teamDelete');button.disabled=true;try{const n=await api('/rest/v1/rpc/delete_team_uploads',{method:'POST',body:{p_ids:ids}});await reload(n+' uploaded leads deleted.')}catch(x){flash(x.message,true)}finally{button.disabled=false}};
}

async function loadLeadRequests(){const p=new URLSearchParams({select:'*',order:'created_at.desc,id.desc',limit:String(S.pageSize),offset:String((S.requestPage-1)*S.pageSize)});const r=await apiPage('/rest/v1/lead_requests?'+p);S.requests=r.data||[];S.requestCount=Number(r.count||0);if(S.requestPage>pageCount(S.requestCount)){S.requestPage=pageCount(S.requestCount);return loadLeadRequests()}}
async function requestLeadsModal(){try{const route=await api('/rest/v1/rpc/my_lead_request_route',{method:'POST',body:{}});modal('<h2>Request leads</h2><p>Send to <strong>'+esc(route.recipient_name)+'</strong> · '+esc(route.recipient_role)+' · '+esc(divisionLabel(route.division))+'</p><form id="requestLeadsForm" class="stack"><div class="field"><label for="requestType">Lead type / batch</label><input id="requestType" required maxlength="120" placeholder="e.g. AIL or Mortgage Protection" list="requestTypes"><datalist id="requestTypes">'+(S.myFolders||[]).filter(x=>x.lead_type).map(x=>'<option value="'+esc(x.lead_type)+'"></option>').join('')+'</datalist></div><div class="field"><label for="requestQuantity">How many leads?</label><input id="requestQuantity" type="number" min="1" max="10000" step="1" required value="100"></div><div class="field"><label for="requestNote">Note (optional)</label><textarea id="requestNote" maxlength="1000" placeholder="Preferred state or other details"></textarea></div><div id="requestError" role="alert"></div><div class="row"><button type="button" id="cancel" class="btn secondary">Cancel</button><button class="btn primary">Send request</button></div></form>');q('#cancel').onclick=closeModal;q('#requestLeadsForm').onsubmit=async e=>{e.preventDefault();const type=q('#requestType').value.trim(),quantity=Number(q('#requestQuantity').value),note=q('#requestNote').value.trim();if(!type||!Number.isInteger(quantity)||quantity<1||quantity>10000)return;const b=e.submitter;b.disabled=true;try{await api('/rest/v1/lead_requests',{method:'POST',headers:{Prefer:'return=minimal'},body:{lead_type:type,quantity,note}});closeModal();S.tab='lead-requests';S.requestPage=1;await reload('Lead request sent.')}catch(x){q('#requestError').className='error';q('#requestError').textContent=x.message;b.disabled=false}}}catch(x){flash(x.message,true)}}
function leadRequestsPage(){return '<div class="head"><div><h1>Lead requests</h1><p>'+(S.profile.role==='admin'?'Requests from your agents. Assign leads through Lead Pool, then mark the request handled.':S.profile.is_team_leader?'Your requests and requests from your team.':'Track requests sent to your team leader or division admin.')+'</p></div></div><div class="tools">'+(S.profile.role==='agent'?'<button class="btn primary requestLeads">Request leads</button>':'')+'<button id="refreshRequests" class="btn secondary">Refresh requests</button></div>'+pager('requests',S.requestPage,S.requestCount)+'<div class="table"><table><thead><tr><th>Agent</th><th>Sent to</th><th>Division</th><th>Lead type</th><th>Quantity</th><th>Note</th><th>Status / reply</th><th>Requested</th><th></th></tr></thead><tbody>'+(S.requests.length?S.requests.map(r=>{const manage=S.profile.role==='admin'||(S.profile.is_team_leader&&r.agent_id!==S.profile.id);return '<tr><td>'+esc(r.agent_name)+'</td><td>'+esc(r.recipient_name)+'</td><td>'+esc(divisionLabel(r.division))+'</td><td>'+esc(r.lead_type)+'</td><td>'+Number(r.quantity).toLocaleString()+'</td><td><div class="callnotes-view">'+esc(r.note||'—')+'</div></td><td><strong>'+esc(r.status==='completed'?'Handled':r.status==='declined'?'Declined':'Pending')+'</strong><div class="callnotes-view">'+esc(r.response||'')+'</div></td><td>'+esc(new Date(r.created_at).toLocaleString())+'</td><td>'+(manage&&r.status==='pending'?'<button class="btn secondary respondRequest" data-id="'+r.id+'">Respond</button>':'')+'</td></tr>'}).join(''):'<tr><td colspan="9" class="empty">No lead requests yet.</td></tr>')+'</tbody></table></div>'+pager('requests',S.requestPage,S.requestCount)}
function bindLeadRequests(){qa('.requestLeads').forEach(b=>b.onclick=requestLeadsModal);if(q('#refreshRequests'))q('#refreshRequests').onclick=async()=>{try{await loadLeadRequests();render()}catch(x){flash(x.message,true)}};qa('.respondRequest').forEach(b=>b.onclick=()=>{const r=S.requests.find(x=>x.id===b.dataset.id);modal('<h2>Respond to '+esc(r.agent_name)+'</h2><p>'+Number(r.quantity)+' '+esc(r.lead_type)+' leads requested. This response does not assign leads automatically.</p><form id="respondRequestForm" class="stack"><div class="field"><label>Response</label><textarea id="requestResponse" maxlength="1000" placeholder="Update for the agent"></textarea></div><div class="field"><label>Status</label><select id="requestStatus"><option value="pending">Pending</option><option value="completed">Handled</option><option value="declined">Declined</option></select></div><div id="responseError" role="alert"></div><div class="row"><button id="cancel" type="button" class="btn secondary">Cancel</button><button class="btn primary">Save response</button></div></form>');q('#requestResponse').value=r.response||'';q('#cancel').onclick=closeModal;q('#respondRequestForm').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const result=await api('/rest/v1/lead_requests?id=eq.'+r.id+'&status=eq.pending',{method:'PATCH',headers:{Prefer:'return=representation'},body:{status:q('#requestStatus').value,response:q('#requestResponse').value.trim()}});if(!result?.length)throw new Error('This request changed or is no longer available. Refresh requests.');closeModal();await reload('Response saved.')}catch(x){q('#responseError').className='error';q('#responseError').textContent=x.message;e.submitter.disabled=false}}})}

// Update only the navigation badge; leave open forms and lead rows intact.
let requestBadgeTimer=null,requestBadgeBusy=false;
function canReceiveLeadRequests(){return !!(S.session&&S.profile?.active&&(S.profile.role==='admin'||(S.profile.is_team_leader&&!S.mfaMode)))}
function requestBadgeMarkup(){const n=Number(S.pendingRequestCount||0);return canReceiveLeadRequests()&&n>0?'<span class="request-count-badge" aria-hidden="true">'+(n>99?'99+':n)+'</span>':''}
function paintRequestBadge(){const b=q('[data-tab="lead-requests"]');if(!b)return;b.querySelector('.request-count-badge')?.remove();b.insertAdjacentHTML('beforeend',requestBadgeMarkup());const n=canReceiveLeadRequests()?Number(S.pendingRequestCount||0):0;const label='Lead requests'+(n?', '+n+' pending':'');b.setAttribute('aria-label',label);b.title=label}
async function refreshRequestBadge(){if(!canReceiveLeadRequests()){S.pendingRequestCount=0;paintRequestBadge();return}if(requestBadgeBusy||document.visibilityState==='hidden')return;requestBadgeBusy=true;const user=S.profile.id;try{const p=new URLSearchParams({select:'id',status:'eq.pending',agent_id:'neq.'+user,limit:'1'});const r=await apiPage('/rest/v1/lead_requests?'+p);if(S.profile?.id===user&&canReceiveLeadRequests()){S.pendingRequestCount=Number(r.count||0);paintRequestBadge()}}catch{/* Keep the last known count during a temporary connection error. */}finally{requestBadgeBusy=false}}
function startRequestBadge(){paintRequestBadge();void refreshRequestBadge();if(!requestBadgeTimer)requestBadgeTimer=setInterval(()=>{void refreshRequestBadge()},30000)}
function stopRequestBadge(){if(requestBadgeTimer)clearInterval(requestBadgeTimer);requestBadgeTimer=null;S.pendingRequestCount=0}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&requestBadgeTimer)void refreshRequestBadge()});

function scriptDivision(){return S.profile.role==='admin'&&adminDivisionList().includes(S.scriptDivision)?S.scriptDivision:S.profile.division}
async function loadSalesScripts(){const p=new URLSearchParams({select:'*',division:'eq.'+scriptDivision(),order:'created_at.desc,id.desc',limit:String(S.pageSize),offset:String((S.scriptPage-1)*S.pageSize)});const r=await apiPage('/rest/v1/sales_scripts?'+p);S.scripts=r.data||[];S.scriptCount=Number(r.count||0);if(S.scriptPage>pageCount(S.scriptCount)){S.scriptPage=pageCount(S.scriptCount);return loadSalesScripts()}if(!S.scripts.some(x=>x.id===S.openScript))S.openScript=S.scripts[0]?.id||null}
function salesScriptsPage(){const admin=S.profile.role==='admin',current=S.scripts.find(x=>x.id===S.openScript);return '<div class="head"><div><h1>Sales scripts</h1><p>Call scripts for '+esc(divisionLabel(scriptDivision()))+'.</p></div></div><div class="tools">'+(hasMultipleAdminDivisions()?'<select id="scriptDivision" aria-label="Script division">'+adminDivisionList().map(d=>'<option value="'+d+'" '+(d===scriptDivision()?'selected':'')+'>'+esc(divisionLabel(d))+'</option>').join('')+'</select>':'')+(admin?'<button id="addScript" class="btn primary">Add script</button>':'')+'</div>'+pager('scripts',S.scriptPage,S.scriptCount)+'<div class="sales-script-layout"><nav class="script-list" aria-label="Sales scripts">'+S.scripts.map(x=>'<button class="script-card '+(x.id===S.openScript?'selected':'')+'" data-script="'+x.id+'" aria-pressed="'+(x.id===S.openScript)+'"><strong>'+esc(x.title)+'</strong><span>'+esc(x.lead_type||'General script')+'</span></button>').join('')+'</nav><article class="script-reader">'+(current?'<div class="head"><div><h2>'+esc(current.title)+'</h2><p>'+esc(current.lead_type||'General script')+'</p></div>'+(admin?'<div class="row"><button id="editScript" class="btn secondary">Edit</button><button id="deleteScript" class="btn danger">Delete</button></div>':'')+'</div><div class="script-body">'+esc(current.body)+'</div>':'<p class="empty">'+(admin?'No scripts yet. Click Add script to paste your first call script.':'Your division admin has not added scripts yet.')+'</p>')+'</article></div>'}
function scriptEditor(id){if(S.profile.role!=='admin')return;const script=S.scripts.find(x=>x.id===id);modal('<h2>'+(script?'Edit':'Add')+' sales script</h2><p>'+esc(divisionLabel(scriptDivision()))+'</p><form id="scriptForm" class="stack"><div class="field"><label for="scriptTitle">Title</label><input id="scriptTitle" required maxlength="160"></div><div class="field"><label for="scriptType">Lead type (optional)</label><input id="scriptType" maxlength="120" placeholder="e.g. Mortgage Protection"></div><div class="field"><label for="scriptBody">Script</label><textarea id="scriptBody" required maxlength="50000" rows="16" placeholder="Type or paste your script here..."></textarea></div><div id="scriptError" role="alert"></div><div class="row"><button id="cancel" type="button" class="btn secondary">Cancel</button><button class="btn primary">Save script</button></div></form>');q('#scriptTitle').value=script?.title||'';q('#scriptType').value=script?.lead_type||'';q('#scriptBody').value=script?.body||'';q('#cancel').onclick=closeModal;q('#scriptForm').onsubmit=async e=>{e.preventDefault();const title=q('#scriptTitle').value.trim(),body=q('#scriptBody').value.trim(),lead_type=q('#scriptType').value.trim();if(!title||!body)return;e.submitter.disabled=true;try{const result=await api('/rest/v1/sales_scripts'+(script?'?id=eq.'+script.id:''),{method:script?'PATCH':'POST',headers:{Prefer:'return=representation'},body:script?{title,body,lead_type}:{title,body,lead_type,division:scriptDivision()}});if(!result?.length)throw new Error('Script no longer available. Refresh and try again.');S.openScript=result[0].id;if(!script)S.scriptPage=1;closeModal();await loadSalesScripts();flash('Script saved.')}catch(x){if(q('#scriptError')){q('#scriptError').className='error';q('#scriptError').textContent=x.message;e.submitter.disabled=false}else flash(x.message,true)}}}
function bindSalesScripts(){if(S.tab!=='sales-scripts')return;qa('[data-script]').forEach(b=>b.onclick=()=>{S.openScript=b.dataset.script;render()});if(q('#scriptDivision'))q('#scriptDivision').onchange=async e=>{S.scriptDivision=e.target.value;S.scriptPage=1;S.openScript=null;try{await loadSalesScripts();render()}catch(x){flash(x.message,true)}};if(q('#addScript'))q('#addScript').onclick=()=>scriptEditor();if(q('#editScript'))q('#editScript').onclick=()=>scriptEditor(S.openScript);if(q('#deleteScript'))q('#deleteScript').onclick=async()=>{if(!confirm('Delete this sales script?'))return;try{await api('/rest/v1/sales_scripts?id=eq.'+S.openScript,{method:'DELETE'});await loadSalesScripts();flash('Script deleted.')}catch(x){flash(x.message,true)}}}
async function loadMasterLeadView(){if(!S.extraLeadDivisions.includes('owner'))throw new Error('Master lead viewing is not enabled for this account.');const r=await apiPage('/rest/v1/leads?'+buildLeadParams({division:'owner',page:S.masterLeadPage,search:S.masterLeadSearch,order:'created_at.desc,id.desc'}));S.masterLeadRows=r.data||[];S.masterLeadCount=Number(r.count||0);if(S.masterLeadPage>pageCount(S.masterLeadCount)){S.masterLeadPage=pageCount(S.masterLeadCount);return loadMasterLeadView()}}
function masterLeadView(){const rows=S.masterLeadRows,cols=csvColumns(rows);return '<div class="head"><div><h1>Owner / Master leads</h1><p>Read-only access to Owner / Master leads.</p></div></div><form id="masterLeadSearch" class="tools"><input id="masterLeadQuery" class="search" aria-label="Search Master leads" placeholder="Search leads" value="'+esc(S.masterLeadSearch)+'"><button class="btn secondary">Search</button></form>'+pager('master-view',S.masterLeadPage,S.masterLeadCount)+'<div id="leadTopScroll" class="topscroll"><div id="leadTopScrollInner" class="topscroll-inner"></div></div><div id="leadTableScroll" class="table csvtable"><table><thead><tr><th>Lead type</th><th>Assignment status</th><th>Call status</th>'+cols.map(c=>'<th>'+esc(c.label)+'</th>').join('')+'<th>Call notes</th></tr></thead><tbody>'+(rows.length?rows.map(l=>'<tr><td>'+esc(l.lead_type||'Unlabeled')+'</td><td>'+esc(l.status)+'</td><td>'+leadStatusBadge(l.agent_status)+'</td>'+cols.map(c=>'<td>'+esc(csvValue(l,c)||'—')+'</td>').join('')+'<td>'+esc(l.call_notes||'—')+'</td></tr>').join(''):'<tr><td colspan="'+(cols.length+4)+'" class="empty">No matching leads.</td></tr>')+'</tbody></table></div>'+pager('master-view',S.masterLeadPage,S.masterLeadCount)}
function bindMasterLeadView(){if(S.tab!=='master-view')return;bindLeadTopScroll();q('#masterLeadSearch').onsubmit=async e=>{e.preventDefault();S.masterLeadSearch=q('#masterLeadQuery').value;S.masterLeadPage=1;try{await loadMasterLeadView();render()}catch(x){flash(x.message,true)}}}
