function canManageTeam(agent){return !!(agent&&!agent.archived&&S.profile?.role==='admin'&&S.profile.active&&(S.profile.is_super_admin||S.profile.division===agent.division));}
function teamSettingsModal(id){
 const agent=S.agents.find(a=>a.id===id);if(!canManageTeam(agent))return;
 const leaders=S.agents.filter(a=>a.id!==id&&a.is_team_leader&&a.active&&!a.archived&&a.division===agent.division);
 modal('<h2>Team settings: '+esc(agent.full_name)+'</h2><form id="teamForm" class="stack"><label><input id="isTeamLeader" type="checkbox" '+(agent.is_team_leader?'checked':'')+'> Team leader — may upload leads and delete only their own non-closed uploads</label><div class="field"><label>Assigned team leader</label><select id="teamLeader"><option value="">No team leader</option>'+leaders.map(a=>'<option value="'+a.id+'" '+(a.id===agent.team_leader_id?'selected':'')+'>'+esc(a.full_name)+'</option>').join('')+'</select></div><div class="notice">Team members and their leader must be in the same division. Division admins can manage their own division; the Master Admin can manage every division.</div><div id="teamError" role="status"></div><div class="row"><button type="button" class="btn secondary" id="cancel">Cancel</button><button class="btn primary">Save team settings</button></div></form>');
 const sync=()=>{q('#teamLeader').disabled=q('#isTeamLeader').checked;if(q('#isTeamLeader').checked)q('#teamLeader').value=''};q('#isTeamLeader').onchange=sync;sync();q('#cancel').onclick=closeModal;
 q('#teamForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{await api('/rest/v1/rpc/set_agent_team',{method:'POST',body:{p_agent:id,p_is_leader:q('#isTeamLeader').checked,p_leader:q('#teamLeader').value||null}});closeModal();await reload('Team settings saved.')}catch(x){q('#teamError').className='error';q('#teamError').textContent=x.message}finally{button.disabled=false}};
}
async function loadMyUploads(){
 const params=new URLSearchParams({select:'*',uploaded_by:'eq.'+S.profile.id,division:'eq.'+S.profile.division,order:'created_at.desc,id.desc',limit:String(S.pageSize),offset:String((S.uploadPage-1)*S.pageSize)});
 const result=await apiPage('/rest/v1/leads?'+params);S.uploads=result.data;S.uploadCount=result.count;
 if(S.uploadPage>pageCount(S.uploadCount)){S.uploadPage=pageCount(S.uploadCount);return loadMyUploads()}
}
function myUploads(){
 const rows=S.uploads||[];
 return '<div class="head"><div><h1>My uploads</h1><p>Leads you added to '+esc(divisionLabel(S.profile.division))+'. Your admin assigns them to agents.</p></div></div><div class="tools"><button id="teamAddLead" class="btn primary">Add lead</button><button id="teamImport" class="btn secondary">Import CSV</button><button id="teamDelete" class="btn danger">Delete selected uploads</button></div><div class="notice">You can delete only leads you uploaded. Closed business is protected. Older uploads without a verified uploader remain under admin control.</div>'+pager('uploads',S.uploadPage,S.uploadCount)+'<div class="table"><table><thead><tr><th>Select</th><th>Name</th><th>Phone</th><th>Lead type / batch</th><th>Status</th><th>Source file</th></tr></thead><tbody>'+(rows.length?rows.map(l=>'<tr><td><input class="teamUploadCheck" type="checkbox" value="'+l.id+'" '+(l.status==='closed'?'disabled':'')+'></td><td>'+esc((l.first_name||'')+' '+(l.last_name||''))+'</td><td>'+esc(l.phone)+'</td><td>'+esc(l.lead_type??'Unlabeled')+'</td><td>'+esc(l.status)+'</td><td>'+esc(l.csv_filename)+'</td></tr>').join(''):'<tr><td colspan="6" class="empty">No uploads yet.</td></tr>')+'</tbody></table></div>'+pager('uploads',S.uploadPage,S.uploadCount);
}
function bindMyUploads(){
 q('#teamAddLead').onclick=addLeadModal;q('#teamImport').onclick=importCsvModal;
 q('#teamDelete').onclick=async()=>{const ids=qa('.teamUploadCheck:checked').map(x=>x.value);if(!ids.length)return flash('Select the uploads you want to delete.',true);if(!confirm('Permanently delete '+ids.length+' of your uploaded leads? This also removes any open assignments for those leads.'))return;const button=q('#teamDelete');button.disabled=true;try{const n=await api('/rest/v1/rpc/delete_team_uploads',{method:'POST',body:{p_ids:ids}});await reload(n+' uploaded leads deleted.')}catch(x){flash(x.message,true)}finally{button.disabled=false}};
}

async function loadLeadRequests(){const p=new URLSearchParams({select:'*',order:'created_at.desc,id.desc',limit:String(S.pageSize),offset:String((S.requestPage-1)*S.pageSize)});const r=await apiPage('/rest/v1/lead_requests?'+p);S.requests=r.data||[];S.requestCount=Number(r.count||0);if(S.requestPage>pageCount(S.requestCount)){S.requestPage=pageCount(S.requestCount);return loadLeadRequests()}}
async function requestLeadsModal(){try{const route=await api('/rest/v1/rpc/my_lead_request_route',{method:'POST',body:{}});modal('<h2>Request leads</h2><p>Send to <strong>'+esc(route.recipient_name)+'</strong> · '+esc(route.recipient_role)+' · '+esc(divisionLabel(route.division))+'</p><form id="requestLeadsForm" class="stack"><div class="field"><label for="requestType">Lead type / batch</label><input id="requestType" required maxlength="120" placeholder="e.g. AIL or Mortgage Protection" list="requestTypes"><datalist id="requestTypes">'+(S.myFolders||[]).filter(x=>x.lead_type).map(x=>'<option value="'+esc(x.lead_type)+'"></option>').join('')+'</datalist></div><div class="field"><label for="requestQuantity">How many leads?</label><input id="requestQuantity" type="number" min="1" max="10000" step="1" required value="100"></div><div class="field"><label for="requestNote">Note (optional)</label><textarea id="requestNote" maxlength="1000" placeholder="Preferred state or other details"></textarea></div><div id="requestError" role="alert"></div><div class="row"><button type="button" id="cancel" class="btn secondary">Cancel</button><button class="btn primary">Send request</button></div></form>');q('#cancel').onclick=closeModal;q('#requestLeadsForm').onsubmit=async e=>{e.preventDefault();const type=q('#requestType').value.trim(),quantity=Number(q('#requestQuantity').value),note=q('#requestNote').value.trim();if(!type||!Number.isInteger(quantity)||quantity<1||quantity>10000)return;const b=e.submitter;b.disabled=true;try{await api('/rest/v1/lead_requests',{method:'POST',headers:{Prefer:'return=minimal'},body:{lead_type:type,quantity,note}});closeModal();S.tab='lead-requests';S.requestPage=1;await reload('Lead request sent.')}catch(x){q('#requestError').className='error';q('#requestError').textContent=x.message;b.disabled=false}}}catch(x){flash(x.message,true)}}
function leadRequestsPage(){return '<div class="head"><div><h1>Lead requests</h1><p>'+(S.profile.role==='admin'?'Requests from your agents. Assign leads through Lead Pool, then mark the request handled.':S.profile.is_team_leader?'Your requests and requests from your team.':'Track requests sent to your team leader or division admin.')+'</p></div></div><div class="tools">'+(S.profile.role==='agent'?'<button class="btn primary requestLeads">Request leads</button>':'')+'<button id="refreshRequests" class="btn secondary">Refresh requests</button></div>'+pager('requests',S.requestPage,S.requestCount)+'<div class="table"><table><thead><tr><th>Agent</th><th>Sent to</th><th>Division</th><th>Lead type</th><th>Quantity</th><th>Note</th><th>Status / reply</th><th>Requested</th><th></th></tr></thead><tbody>'+(S.requests.length?S.requests.map(r=>{const manage=S.profile.role==='admin'||(S.profile.is_team_leader&&r.agent_id!==S.profile.id);return '<tr><td>'+esc(r.agent_name)+'</td><td>'+esc(r.recipient_name)+'</td><td>'+esc(divisionLabel(r.division))+'</td><td>'+esc(r.lead_type)+'</td><td>'+Number(r.quantity).toLocaleString()+'</td><td><div class="callnotes-view">'+esc(r.note||'—')+'</div></td><td><strong>'+esc(r.status==='completed'?'Handled':r.status==='declined'?'Declined':'Pending')+'</strong><div class="callnotes-view">'+esc(r.response||'')+'</div></td><td>'+esc(new Date(r.created_at).toLocaleString())+'</td><td>'+(manage&&r.status==='pending'?'<button class="btn secondary respondRequest" data-id="'+r.id+'">Respond</button>':'')+'</td></tr>'}).join(''):'<tr><td colspan="9" class="empty">No lead requests yet.</td></tr>')+'</tbody></table></div>'+pager('requests',S.requestPage,S.requestCount)}
function bindLeadRequests(){qa('.requestLeads').forEach(b=>b.onclick=requestLeadsModal);if(q('#refreshRequests'))q('#refreshRequests').onclick=async()=>{try{await loadLeadRequests();render()}catch(x){flash(x.message,true)}};qa('.respondRequest').forEach(b=>b.onclick=()=>{const r=S.requests.find(x=>x.id===b.dataset.id);modal('<h2>Respond to '+esc(r.agent_name)+'</h2><p>'+Number(r.quantity)+' '+esc(r.lead_type)+' leads requested. This response does not assign leads automatically.</p><form id="respondRequestForm" class="stack"><div class="field"><label>Response</label><textarea id="requestResponse" maxlength="1000" placeholder="Update for the agent"></textarea></div><div class="field"><label>Status</label><select id="requestStatus"><option value="pending">Pending</option><option value="completed">Handled</option><option value="declined">Declined</option></select></div><div id="responseError" role="alert"></div><div class="row"><button id="cancel" type="button" class="btn secondary">Cancel</button><button class="btn primary">Save response</button></div></form>');q('#requestResponse').value=r.response||'';q('#cancel').onclick=closeModal;q('#respondRequestForm').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const result=await api('/rest/v1/lead_requests?id=eq.'+r.id+'&status=eq.pending',{method:'PATCH',headers:{Prefer:'return=representation'},body:{status:q('#requestStatus').value,response:q('#requestResponse').value.trim()}});if(!result?.length)throw new Error('This request changed or is no longer available. Refresh requests.');closeModal();await reload('Response saved.')}catch(x){q('#responseError').className='error';q('#responseError').textContent=x.message;e.submitter.disabled=false}}})}

// Update only the navigation badge; leave open forms and lead rows intact.
let requestBadgeTimer=null,requestBadgeBusy=false;
function canReceiveLeadRequests(){return !!(S.session&&S.profile?.active&&(S.profile.role==='admin'||(S.profile.is_team_leader&&!S.mfaMode)))}
function requestBadgeMarkup(){const n=Number(S.pendingRequestCount||0);return canReceiveLeadRequests()&&n>0?'<span class="request-count-badge" aria-hidden="true">'+(n>99?'99+':n)+'</span>':''}
function paintRequestBadge(){const b=q('[data-tab="lead-requests"]');if(!b)return;b.querySelector('.request-count-badge')?.remove();b.insertAdjacentHTML('beforeend',requestBadgeMarkup());const n=canReceiveLeadRequests()?Number(S.pendingRequestCount||0):0;const label='Lead requests'+(n?', '+n+' pending':'');b.setAttribute('aria-label',label);b.title=label}
async function refreshRequestBadge(){if(!canReceiveLeadRequests()){S.pendingRequestCount=0;paintRequestBadge();return}if(requestBadgeBusy||document.visibilityState==='hidden')return;requestBadgeBusy=true;const user=S.profile.id;try{const p=new URLSearchParams({select:'id',status:'eq.pending',agent_id:'neq.'+user,limit:'1'});const r=await apiPage('/rest/v1/lead_requests?'+p);if(S.profile?.id===user&&canReceiveLeadRequests()){S.pendingRequestCount=Number(r.count||0);paintRequestBadge()}}catch{/* Keep the last known count during a temporary connection error. */}finally{requestBadgeBusy=false}}
function startRequestBadge(){paintRequestBadge();void refreshRequestBadge();if(!requestBadgeTimer)requestBadgeTimer=setInterval(()=>{void refreshRequestBadge()},30000)}
function stopRequestBadge(){if(requestBadgeTimer)clearInterval(requestBadgeTimer);requestBadgeTimer=null;S.pendingRequestCount=0}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&requestBadgeTimer)void refreshRequestBadge()});
