'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{createHmac}=require('node:crypto');
process.env.STRIPE_SECRET_KEY='sk_test_mock';process.env.SUPABASE_SECRET_KEY='sb_secret_mock';
for(const [key,prefix]of [['TWILIO_ACCOUNT_SID','AC'],['TWILIO_API_KEY_SID','SK'],['TWILIO_TWIML_APP_SID','AP']])process.env[key]=prefix+'a'.repeat(32);
process.env.TWILIO_AUTH_TOKEN='mock';process.env.TWILIO_API_KEY_SECRET='mock';process.env.TWILIO_PHONE_NUMBER='+13133624204';process.env.TWILIO_TEST_PHONE_NUMBER='+12482383969';
const full=require('../lib/dialer-full'),billing=require('../lib/dialer-full-billing'),numbers=require('../lib/dialer-full-numbers');
const user={id:full.MASTER,live:false,sessionId:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'},callId='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',parent='CA'+'b'.repeat(32),phone='+12487755796',key='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const account={customer_id:'cus_mock123',subscription_status:'active',paid_invoice:true,subscription_id:'sub_mock123'};
let existing=true,subscriptions=[],pending=false,owned=null,purchases=0,quote=null,invoiceItems=new Map(),fees=0,posts=[];
const result=d=>({ok:true,status:200,json:async()=>d,text:async()=>JSON.stringify(d)});
global.fetch=async(url,o={})=>{
 if(url.includes('/rpc/')){const name=url.split('/').pop(),b=JSON.parse(o.body);posts.push({name,b});switch(name){case 'dialer_session_valid':return result(true);case 'dialer_get_account':return result(existing?account:{});case 'dialer_set_customer':existing=true;return result(account);case 'dialer_sync_subscription':return result(account);case 'dialer_claim_checkout':return result({...account,checkout_request:key,checkout_expires:new Date(Date.now()+3600000).toISOString()});case 'dialer_set_checkout':return result(null);case 'dialer_begin_number':return result({state:'provisioning',phone,purchase_key:key});case 'dialer_claim_number_purchase':return result(purchases===0);case 'dialer_finish_number':return result(null);case 'dialer_consume_call':return result({userId:user.id,to:process.env.TWILIO_TEST_PHONE_NUMBER,callerId:phone,maxSeconds:1800});case 'dialer_quote_overage':if(pending)throw full.failure(409,'Call reconciliation is still pending');return result(quote||{amount_cents:60,used_minutes:5020,invoice_item_id:null});default:throw Error('Unexpected RPC '+name);}}
 if(url.includes('/auth/v1/user'))return result({id:user.id,email:'test@example.invalid'});
 if(url.includes('/profiles?'))return result([{id:user.id,role:'admin',active:true,archived:false}]);
 if(url.includes('/rest/v1/dialer_calls?'))return result(pending?[{parent_sid:parent,created_at:new Date().toISOString()}]:[]);
 if(url.includes('/rest/v1/dialer_periods?'))return result([{starts_at:'2026-09-01T00:00:00.000Z',ends_at:'2026-10-01T00:00:00.000Z'}]);
 if(url.includes('/rest/v1/dialer_overage_invoices?')){if(o.method==='PATCH'){quote={...quote,...JSON.parse(o.body)};return result([quote]);}return result(quote?[quote]:[]);}
 if(url.includes('api.stripe.com')){if(url.includes('/webhook_endpoints?'))return result({data:[{id:'we_mock',url:full.ORIGIN+'/api/dialer/stripe-webhook',status:'enabled',livemode:false,enabled_events:['*']}]});const b=new URLSearchParams(o.body||'');if(url.includes('/subscriptions?'))return result({has_more:false,data:subscriptions});if(url.endsWith('/customers'))return result({id:account.customer_id,livemode:false});if(url.endsWith('/checkout/sessions')){assert.equal(b.get('line_items[0][price_data][unit_amount]'),'25000');assert.equal(b.get('customer'),account.customer_id);assert.equal(b.get('subscription_data[metadata][portal_user_id]'),user.id);assert.ok(o.headers['Idempotency-Key'].endsWith(key));return result({id:'cs_test_mock1234567890123',livemode:false,url:'https://checkout.stripe.com/test/mock'});}if(url.endsWith('/invoiceitems')){assert.equal(b.get('invoice'),'in_mock123');assert.equal(b.get('amount'),'60');const idem=o.headers['Idempotency-Key'];if(!invoiceItems.has(idem)){invoiceItems.set(idem,{id:'ii_mock123'});fees++;}return result(invoiceItems.get(idem));}if(url.endsWith('/invoices/in_mock123'))return result({id:'in_mock123',status:'draft'});throw Error('Unexpected Stripe '+url);}
 if(url.includes('api.twilio.com')){if(url.includes('Calls.json?ParentCallSid='))return result({calls:[{sid:'CA'+'d'.repeat(32),status:'in-progress'}]});if(url.includes('IncomingPhoneNumbers.json?'))return result({incoming_phone_numbers:owned?[owned]:[]});if(url.endsWith('IncomingPhoneNumbers.json')&&o.method==='POST'){purchases++;const b=new URLSearchParams(o.body);owned={sid:'PN'+'f'.repeat(32),phone_number:phone,friendly_name:b.get('FriendlyName')};assert.equal(b.get('VoiceUrl'),full.ORIGIN+'/dialer-inbound.xml');throw Error('Simulated timeout after provider purchase');}throw Error('Unexpected Twilio '+url);}
 throw Error('Unexpected request '+url);
};
const jwt='x.'+Buffer.from(JSON.stringify({sub:user.id,aal:'aal2',exp:Math.floor(Date.now()/1000)+300,session_id:user.sessionId})).toString('base64url')+'.x';
const request=b=>({method:'POST',headers:{origin:full.ORIGIN,authorization:'Bearer '+jwt},body:b});
const response=()=>({setHeader(){},status(c){this.code=c;return this;},json(d){this.data=d;return this;},send(d){this.data=d;return this;}});
(async()=>{
 const tokens=full.callTokens(user,callId,full.config());assert.equal(full.grant(tokens.callGrant,full.config()).callId,callId);assert.throws(()=>full.grant(tokens.callGrant.slice(0,-2)+'xx',full.config()));
 assert.equal(full.identity(user.id),'vivid_'+user.id.replace(/-/g,''));process.env.STRIPE_SECRET_KEY='sk_live_mock';assert.throws(()=>full.mode());process.env.STRIPE_SECRET_KEY='sk_test_mock';
 let r=response();await require('../api/dialer/account')(request({action:'invalid'}),r);assert.equal(r.code,400);r=response();await require('../api/dialer/account')({...request({action:'state'}),headers:{}},r);assert.equal(r.code,403);
 await billing.checkout(user);assert.equal(posts.find(p=>p.name==='dialer_claim_checkout').b.p_user,user.id);
 const sub={id:account.subscription_id,customer:account.customer_id,livemode:false,status:'active',created:1,metadata:{purpose:full.PURPOSE,portal_user_id:user.id},latest_invoice:{status:'paid',paid:true},items:{data:[{quantity:1,current_period_start:Math.floor(Date.now()/1000)-86400,current_period_end:Math.floor(Date.now()/1000)+86400,price:{unit_amount:25000,currency:'usd',recurring:{interval:'month',interval_count:1}}}]}};
 subscriptions=[sub];await billing.sync(user);assert.equal(posts.filter(p=>p.name==='dialer_sync_subscription').at(-1).b.p_snapshot.paid,true);
 subscriptions=[{...sub,metadata:{purpose:full.PURPOSE,portal_user_id:'foreign'}}];await billing.sync(user);subscriptions=[{...sub,customer:'cus_foreign'}];await assert.rejects(()=>billing.sync(user),/does not belong/);subscriptions=[sub,{...sub,id:'sub_duplicate'}];await assert.rejects(()=>billing.sync(user),/Multiple subscriptions/);subscriptions=[sub];
 const invoice={id:'in_mock123',customer:account.customer_id,livemode:false,status:'draft',billing_reason:'subscription_cycle',period_end:1790812800,parent:{subscription_details:{subscription:account.subscription_id}}};
 pending=true;await assert.rejects(()=>billing.overage(user,invoice),/reconciliation/);assert.equal(fees,0);pending=false;await billing.overage(user,invoice);await billing.overage(user,invoice);assert.equal(fees,1,'retry added an extra fee');
 await assert.rejects(()=>numbers.activate(user,{slot:1,phoneNumber:phone,acceptTwilioCharges:false}));assert.equal(purchases,0);await assert.rejects(()=>numbers.activate(user,{slot:1,phoneNumber:phone,acceptTwilioCharges:true}),/pending/);assert.equal(purchases,1);await numbers.activate(user,{slot:1,phoneNumber:phone,acceptTwilioCharges:true});assert.equal(purchases,1,'retry purchased twice');
 const b={AccountSid:process.env.TWILIO_ACCOUNT_SID,From:'client:'+full.identity(user.id),CallSid:parent,CallGrant:tokens.callGrant};let raw=full.ORIGIN+'/api/dialer/voice';for(const k of Object.keys(b).sort())raw+=k+b[k];const req={method:'POST',url:'/api/dialer/voice',headers:{'content-type':'application/x-www-form-urlencoded','x-twilio-signature':createHmac('sha1','mock').update(raw).digest('base64')},body:b};r=response();await require('../api/dialer/voice')(req,r);assert.equal(r.code,200);assert.match(r.data,/callerId="\+12487755796"/);assert.match(r.data,/status-v2/);r=response();await require('../api/dialer/voice')({...req,headers:{...req.headers,'x-twilio-signature':'invalid'}},r);assert.equal(r.code,403);
 for(const f of ['index.html','dialer.html']){const html=fs.readFileSync(__dirname+'/../'+f,'utf8');for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g))if(m[1].trim())new vm.Script(m[1],{filename:f});}
 console.log('PASS: authenticated ownership, live-mode lock, fixed pricing, subscription validation and duplicate detection, signed calls, provider timeout recovery, fee retry protection, UI syntax.');
})().catch(e=>{console.error(e);process.exit(1);});
