const {PGlite}=require('@electric-sql/pglite');
const {pg_trgm}=require('@electric-sql/pglite/contrib/pg_trgm');
const fs=require('fs'),assert=require('assert/strict');
(async()=>{
 const db=new PGlite({extensions:{pg_trgm}});
 await db.exec(`
 create role anon;create role authenticated;create schema auth;create schema extensions;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth to authenticated;
 create type public.user_role as enum('admin','agent');create type public.lead_status as enum('unassigned','assigned','closed');
 create table public.profiles(id uuid primary key,email text,full_name text,role public.user_role,active boolean default true,archived boolean default false,is_super_admin boolean default false,division text);
 create table public.leads(id uuid primary key default gen_random_uuid(),first_name text not null default '',last_name text not null default '',phone text,email text,state text,source text,notes text,lead_type text,division text not null,owner_admin_id uuid,csv_filename text,csv_headers jsonb,csv_values jsonb,assigned_to uuid references public.profiles,created_at timestamptz not null default now(),assigned_at timestamptz,status public.lead_status not null default 'unassigned',agent_status text,call_notes text);
 create table public.closed_business(agent_id uuid,monthly_premium numeric,annual_premium numeric);
 create function public.is_admin() returns boolean language sql stable security definer as $$select exists(select 1 from public.profiles where id=auth.uid() and role='admin' and active)$$;
 create function public.is_super_admin() returns boolean language sql stable security definer as $$select exists(select 1 from public.profiles where id=auth.uid() and role='admin' and active and is_super_admin)$$;
 create function public.current_admin_division() returns text language sql stable security definer as $$select division from public.profiles where id=auth.uid() and role='admin' and active$$;
 create function public.admin_can_access_division(d text) returns boolean language sql stable as $$select public.is_admin() and(public.is_super_admin() or d=public.current_admin_division())$$;
 insert into public.profiles(id,role,is_super_admin,division)values('00000000-0000-0000-0000-000000000001','admin',true,'vivid_life'),('00000000-0000-0000-0000-000000000002','admin',false,'legacy_life'),('00000000-0000-0000-0000-000000000003','admin',false,'vivid_life'),('00000000-0000-0000-0000-000000000004','agent',false,'vivid_life');
 `);
 await db.exec('begin;'+fs.readFileSync('db/large-imports.sql','utf8')+'commit;');
 const asUser=async n=>{await db.exec(`reset role;select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-${String(n).padStart(12,'0')}',false);set role authenticated;`);};
 const jobId='10000000-0000-0000-0000-000000000001';
 await asUser(1);
 await db.query(`insert into public.lead_import_jobs(id,owner_id,division,fingerprint,filename,file_size,lead_type)values($1,auth.uid(),'vivid_life',$2,'test.csv',100,'Test')`,[jobId,'a'.repeat(64)]);
 const payload=[{first_name:'Test',last_name:'Lead',state:'MI',csv_values:['Test','Lead','MI']}];
 const batch=async(from,to,rows=payload,final=false)=> (await db.query('select public.commit_lead_import_batch($1,$2,$3,$4,$5,$6) as result',[jobId,from,to,JSON.stringify(['First Name','Last Name','State']),JSON.stringify(rows),final])).rows[0].result;
 assert.equal((await batch(0,50)).row_count,1);
 assert.equal((await batch(0,50)).replayed,true);
 await assert.rejects(()=>batch(0,50,[{...payload[0],first_name:'Different'}]),/Checkpoint/);
 await assert.rejects(()=>batch(51,75),/Checkpoint/);
 await asUser(2);await assert.rejects(()=>batch(50,75),/Import not found/);
 await assert.rejects(()=>db.query(`insert into public.lead_import_jobs(owner_id,division,fingerprint,filename,file_size,lead_type)values(auth.uid(),'vivid_life',$1,'x',100,'No')`,['b'.repeat(64)]),/row-level security/);
 await asUser(1);await assert.rejects(()=>db.query(`insert into public.lead_import_jobs(owner_id,division,fingerprint,filename,file_size,lead_type)values(auth.uid(),'legacy_life',$1,'x',100,'No')`,['b'.repeat(64)]),/row-level security/);
 await assert.rejects(()=>batch(50,75,[{first_name:'Bad',csv_values:[]} ,{first_name:'Bad',csv_values:'not an array'}]),/Invalid CSV row|array length/);
 assert.equal((await db.query('select row_count from public.lead_import_jobs where id=$1',[jobId])).rows[0].row_count,1);
 assert.equal((await batch(50,100)).row_count,2);
 assert.equal((await batch(100,100,[],true)).status,'completed');
 assert.equal((await batch(100,100,[],true)).replayed,true);
 const stats=(await db.query('select public.admin_dashboard_stats() as s')).rows[0].s;assert.equal(stats.total_leads,2);
 await db.exec('reset role');
 await db.exec(`update public.leads set assigned_to='00000000-0000-0000-0000-000000000004',status='assigned' where id=(select id from public.leads limit 1)`);
 await asUser(1);assert.equal((await db.query('select * from public.admin_agent_stats()')).rows[0].open_leads,1);
 const after=(await db.query('select public.admin_dashboard_stats() as s')).rows[0].s;assert.equal(after.assigned,1);assert.equal(after.unassigned,1);
 await asUser(2);assert.equal((await db.query('select public.admin_dashboard_stats() as s')).rows[0].s.total_leads,0);
 await db.exec('reset role;delete from public.leads');await asUser(1);assert.equal((await db.query('select public.admin_dashboard_stats() as s')).rows[0].s.total_leads,0);
 await asUser(4);await assert.rejects(()=>batch(100,100,[],true),/Active admin/);
 await db.exec('reset role;set role anon');await assert.rejects(()=>db.query('select public.commit_lead_import_batch($1,0,1,$2,$3,false)',[jobId,'[]','[]']),/permission denied/);
 console.log('PASS: migration SQL, atomic batches, replay without duplicates, mismatched retry rejection, checkpoints, completion replay, division isolation, agent/anon denial, incremental totals for insert/update/delete');
 await db.close();
})().catch(e=>{console.error(e.message,e.code,e.detail||'');process.exitCode=1;});
