const fs=require('fs'),path=require('path'),assert=require('assert');
const {chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.LLD_TEST_BROWSER||'/root/.cache/ms-playwright/chromium_headless_shell-1161/chrome-linux/headless_shell'});const page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));let ap=12000,calls=0;
const data=()=>({scopes:['owner','vivid_life'],as_of:new Date().toISOString(),totals:{today_ap:ap,today_deals:2,month_ap:52000,month_mp:4333,month_deals:25,week_ap:18000,week_deals:12,year_ap:180000,year_deals:80,active_producers:3},rankings:[{agent_id:'a',agent_name:'Sample Agent One',ap:24000,deals:10},{agent_id:'b',agent_name:'Sample Agent Two',ap:18000,deals:9},{agent_id:'c',agent_name:'<script>unsafe</script>',ap:10000,deals:6}],today_feed:[{id:String(ap),agent_name:'Sample Agent One',carrier:'Sample Carrier',policy_type:'Whole Life',annual_premium:ap,monthly_premium:ap/12,created_at:new Date().toISOString()}]});
await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname==='cdn.jsdelivr.net')return route.fulfill({contentType:'application/javascript',body:`window.supabase={createClient:()=>({auth:{},realtime:{setAuth:async()=>{}},channel:()=>({on(event,filter,cb){window.testDealEvent=cb;return this},subscribe(cb){window.testChannelStatus=cb;setTimeout(()=>cb('SUBSCRIBED'),0);return this}}),removeChannel:()=>{window.testRemoved=true}})};`});if(u.hostname.includes('supabase.co')){if(u.pathname.endsWith('/live_leaderboard')){calls++;return route.fulfill({json:data()});}return route.fulfill({json:[]});}const p=path.join(process.cwd(),u.pathname==='/'?'index.html':u.pathname);if(fs.existsSync(p))return route.fulfill({body:fs.readFileSync(p),contentType:p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':p.endsWith('.png')?'image/png':'text/html'});return route.fulfill({status:404,body:''});});
await page.goto('https://lld-test.invalid/');await page.evaluate(async()=>{S.session={access_token:'fixture'};S.profile={id:'a',role:'admin',active:true,division:'owner',full_name:'Sample Admin'};S.adminDivisions=['owner','vivid_life'];S.tab='leaderboard';await loadLeaderboard();render();});await page.waitForFunction(()=>document.querySelector('#leaderboardConnection')?.textContent==='Live');assert(await page.locator('.sales-board').isVisible());assert((await page.locator('.sales-rank').innerText()).includes('<script>unsafe</script>'));assert.equal(await page.locator('.sales-rank script').count(),0);
await page.screenshot({path:'/tmp/lld-leaderboard-desktop.png',fullPage:true});const prior=calls;ap=15000;await page.evaluate(()=>window.testDealEvent({}));await page.waitForFunction(()=>document.querySelector('.sales-today-total').textContent.includes('15,000'));assert(calls>prior);assert.equal(await page.locator('.sales-deal-new').count(),1);await page.evaluate(()=>window.testChannelStatus('CHANNEL_ERROR'));assert((await page.locator('#leaderboardConnection').innerText()).includes('Reconnecting'));await page.evaluate(()=>window.testChannelStatus('SUBSCRIBED'));
await page.locator('#leaderboardDivision').selectOption('vivid_life');await page.waitForFunction(()=>LB.data!==null);assert.equal(await page.evaluate(()=>LB.division),'vivid_life');await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/lld-leaderboard-mobile.png',fullPage:true});const width=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth}));assert(width.scroll<=width.viewport+1,JSON.stringify(width));
await page.evaluate(()=>{S.tab='activity';render();});assert(await page.evaluate(()=>window.testRemoved));await page.evaluate(async()=>{resetLeaderboard();S.profile={id:'a',role:'agent',active:true,division:'owner',full_name:'Sample Agent'};S.tab='leaderboard';await loadLeaderboard();render();});assert(await page.locator('.sales-board').isVisible());assert(await page.getByRole('button',{name:'Leaderboard',exact:true}).isVisible());assert.deepEqual(errors,[]);console.log('PASS: desktop/mobile layout; admin and agent navigation; event-driven refresh; reconnect label; division selection; escaped names; subscription cleanup; no JS errors.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
