const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync('index.html','utf8'),source=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(x=>x.startsWith('const BASE='));
const ctx=vm.createContext({URLSearchParams,Intl,Set,Map,Date,Number,String,JSON,localStorage:{getItem:()=>null},window:{supabase:{createClient:()=>({})}},document:{getElementById:()=>({}),querySelector:()=>({}),querySelectorAll:()=>[],addEventListener:()=>{}},setInterval:()=>{}});
vm.runInContext(fs.readFileSync('team-leaders.js','utf8'),ctx);vm.runInContext(source.slice(0,source.lastIndexOf('(async()=>{if(S.session)')),ctx);
vm.runInContext(`S.divisions=['owner','vivid_life','legacy_life'].map(id=>({id}));S.profile={id:'a',role:'admin',active:true,is_super_admin:true,division:'vivid_life',full_name:'Master'};S.agents=[{id:'b',full_name:'Leader',is_team_leader:true,division:'vivid_life',active:true}];`,ctx);

vm.runInContext(fs.readFileSync('divisions.js','utf8'),ctx);
let page=vm.runInContext('leadPage()',ctx);
assert(page.includes('sendDivisionPick'));assert(page.includes('id="pick"'));assert(page.includes('id="assign"'));
vm.runInContext("S.profile.is_super_admin=false;S.adminDivisions=['vivid_life']",ctx);
page=vm.runInContext('leadPage()',ctx);assert(page.includes('id="pick"'));assert(page.includes('id="assign"'));assert(!page.includes('sendDivisionPick'));
vm.runInContext("S.profile.is_super_admin=true;S.adminDivisions=['owner','vivid_life','legacy_life'];S.divisionFilter='legacy_life'",ctx);
page=vm.runInContext('leadPage()',ctx);assert(page.includes('Legacy leads stay in Legacy'));assert(!page.includes('sendDivisionPick'));
console.log('PASS Master agent and division controls, admin assignments, Legacy boundary');
vm.runInContext("S.divisionFilter='vivid_life';S.sendSource=null;S.divisions=[{id:'owner',name:'Master'},{id:'vivid_life',name:'Vivid Life'},{id:'legacy_life',name:'Legacy Life'}];S.agents=[{id:'legacy-agent',full_name:'Legacy Agent',division:'legacy_life',active:true},{id:'vivid-agent',full_name:'Vivid Agent',division:'vivid_life',active:true},{id:'inactive-agent',full_name:'Inactive Agent',division:'legacy_life',active:false}];S.selected=new Set(['lead']);",ctx);
page=vm.runInContext('masterSendControls()',ctx);assert(page.includes('sendRecipientPick'));assert(page.includes('Division lead pool'));
const nodes={'#sendDivisionPick':{value:'legacy_life'},'#sendRecipientPick':{value:'',innerHTML:'',disabled:true},'#sendDivision':{isConnected:true}};ctx.document.querySelector=s=>nodes[s]||null;
vm.runInContext('bindDivisionRecipients()',ctx);nodes['#sendDivisionPick'].onchange();assert(nodes['#sendRecipientPick'].innerHTML.includes('Legacy Agent'));assert(!nodes['#sendRecipientPick'].innerHTML.includes('Vivid Agent'));assert(!nodes['#sendRecipientPick'].innerHTML.includes('Inactive Agent'));assert(!nodes['#sendRecipientPick'].disabled);
nodes['#sendRecipientPick'].value='legacy-agent';nodes['#sendRecipientPick'].onchange();page=vm.runInContext('masterSendControls()',ctx);assert(page.includes('value="legacy-agent" selected'));
ctx.confirm=()=>true;ctx.sent=null;vm.runInContext("api=async(path,opt)=>{sent={path,body:opt.body};return 1};reload=async()=>{};flash=msg=>{throw Error(msg)}",ctx);
(async()=>{await vm.runInContext('sendSelectedToDivision()',ctx);assert.equal(ctx.sent.path,'/rest/v1/rpc/send_leads_to_recipient');assert.equal(ctx.sent.body.p_destination,'legacy_life');assert.equal(ctx.sent.body.p_agent_id,'legacy-agent');assert.equal(ctx.sent.body.p_source,'vivid_life');assert.equal(vm.runInContext('S.selected.size',ctx),0);console.log('PASS destination agent filtering, selection persistence, atomic RPC request');})().catch(e=>{console.error(e);process.exitCode=1});
