'use strict';
const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
class Node{constructor(){this.dataset={};this.value='';this.children=[];this.hidden=false;this.disabled=false;this.textContent='';this.style={};this.parentElement={hidden:false,querySelector:()=>new Node()};this.classList={toggle(){}};}append(...n){this.children.push(...n);}replaceChildren(...n){this.children=n;}setAttribute(k,v){(this.attrs??={})[k]=v;}getAttribute(k){return this.attrs?.[k];}addEventListener(){}click(){return this.onclick?.();}focus(){}get options(){return this.children;}}
const nativeSource=fs.readFileSync(__dirname+'/../portal-dialer.js','utf8');const html=JSON.parse(nativeSource.match(/root\.innerHTML=("(?:\\.|[^"\\])*");/)[1]);const nodes=new Map([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],new Node()]));
const views=['workspace','history','billing','manual'].map(v=>{const n=new Node();n.dataset.view=v;return n;});const root={isConnected:true,querySelector:s=>nodes.get(s.match(/\[id="([^"]+)"\]/)?.[1]),querySelectorAll:s=>s==='[data-view]'?views:[]};
let placed=0,lastCall,refreshes=0,expired=true,timerCallbacks=[],activeTimers=new Set(),timerId=0,events=new Set(),discard=true;const rows=[{id:'one',first_name:'One',phone:'2485550124',agent_status:null,call_notes:null,lead_type:'Pro5'}];
class Call{constructor(){this.handlers={};this.state='open';}on(e,f){this.handlers[e]=f;}status(){return this.state;}disconnect(){this.state='closed';this.handlers.disconnect?.();}mute(){}isMuted(){return false;}sendDigits(){}}
class Device{on(){}async connect(){placed++;lastCall=new Call();return lastCall;}destroy(){}}
const atCost=process.env.TEST_AT_COST==='1';
const sess={access_token:'fake',user:{id:'8139e230-055d-4247-8133-684ed817b4fa'}};
const ctx=vm.createContext({document:{hidden:false,createElement:()=>new Node()},Twilio:{Device},sessionExpiresWithin:()=>expired,refreshToken:async()=>{refreshes++;expired=false;sess.access_token='refreshed';return true;},localStorage:{getItem:()=>JSON.stringify(sess)},location:{href:'',search:''},crypto:{randomUUID:()=> 'mock'},setInterval(fn){timerCallbacks.push(fn);const id=++timerId;activeTimers.add(id);return id;},clearInterval:id=>activeTimers.delete(id),setTimeout(){const id=++timerId;activeTimers.add(id);return id;},clearTimeout:id=>activeTimers.delete(id),addEventListener:(n,f)=>events.add(f),removeEventListener:(n,f)=>events.delete(f),Intl,URL,URLSearchParams,Date,Map,AbortSignal,confirm:()=>discard,console,root,fetch:async(url,o)=>{const b=JSON.parse(o.body);let d;if(url.includes('/account'))d={atCost,atCostPaymentReady:false,actualCostCents:null,livemode:true,ownerExempt:!atCost,entitled:true,realCallingAllowed:true,numbers:[{slot:1,state:'active',phoneNumber:'+13135550102'}],subscriptionStatus:'owner_exempt',usedMinutes:0};else if(b.action==='profile')d={profile:{full_name:'Peter Yelda',division:'vivid_life'},scripts:[]};else if(b.action==='history')d={calls:[]};else if(url.includes('token-v2'))d={token:'token',callGrant:'grant',destination:'2485550124',callerId:'3135550123'};else if(b.action==='folders')d={folders:[{lead_type:'Pro5',lead_count:1}]};else if(b.action==='leads')d={leads:rows.map(r=>({...r}))};else if(b.action==='save'){rows[0].agent_status=b.status;rows[0].call_notes=b.notes;d={lead:{...rows[0]}};}return{ok:true,json:async()=>d};}});
vm.runInContext('window=globalThis',ctx);vm.runInContext(fs.readFileSync(__dirname+'/../portal-dialer.js','utf8'),ctx);vm.runInContext('instance=createPortalDialer(root)',ctx);const run=s=>vm.runInContext(s,ctx),flush=()=>new Promise(r=>setImmediate(r));
(async()=>{await flush();await flush();assert.equal(nodes.get('substatus').textContent,atCost?'Actual-cost billing active':'Master — free');assert.equal(nodes.get('subscribe').hidden,!atCost);assert.ok(!nodes.get('planprice').innerHTML.includes('$250'));if(atCost)assert.equal(nodes.get('subscribe').textContent,'Add payment card');assert.ok(!html.includes('$250'));assert.ok(fs.readFileSync(__dirname+'/../index.html','utf8').includes('/portal-dialer.js?v=20261007-dialer-session-3'));assert.equal(run('typeof render'),'undefined');assert.equal(run('window.updateDialerDisplay'),undefined);assert.ok(activeTimers.size>=4);
 nodes.get('queue').children[0].children[1].click();nodes.get('notes').value='Keep notes';discard=false;assert.equal(run('instance.canLeave()'),false);discard=true;
 root.isConnected=false;root.isConnected=true;assert.equal(nodes.get('notes').value,'Keep notes');nodes.get('calllead').click();await flush();assert.equal(placed,1);assert.equal(run('instance.canLeave()'),false);nodes.get('callhangup').click();assert.equal(run('instance.canLeave()'),false);nodes.get('outcome').value='call_back';nodes.get('save').click();await flush();assert.equal(rows[0].agent_status,'call_back');assert.equal(run('instance.canLeave()'),true);
 views[3].click();assert.equal(nodes.get('manual').hidden,false);assert.equal(nodes.get('workspace').hidden,true);nodes.get('manual-check').click();await flush();nodes.get('manual-caller').value='1';nodes.get('manual-destination').value='2485550124';nodes.get('manual-permission').checked=true;nodes.get('manual-call').click();await flush();assert.equal(placed,2);assert.ok(refreshes>0);sess.access_token='rotated-again';timerCallbacks.forEach(fn=>fn());assert.equal(lastCall.status(),'open');assert.equal(run('instance.canLeave()'),false);nodes.get('manual-hangup').click();assert.equal(run('instance.canLeave()'),true);run('instance.dispose()');assert.equal(activeTimers.size,0);assert.equal(events.size,0);
 const index=fs.readFileSync(__dirname+'/../index.html','utf8');assert.ok(index.includes("await navigatePortalTab('power-dialer')"));assert.ok(!index.includes("location.href='/dialer.html'"));assert.ok(index.includes("if(S.tab==='power-dialer')return;"));const css=fs.readFileSync(__dirname+'/../portal-dialer.css','utf8');assert.ok(css.includes('#portalDialer button{'));assert.ok(!css.includes(':root{'));assert.equal(JSON.parse(fs.readFileSync(__dirname+'/../vercel.json')).redirects[0].destination,'/#power-dialer');console.log('PASS: native portal mounting, isolated variables/styles, free billing, queue retention, lead/manual calls, navigation locks, timer cleanup and old URL redirect.');})().catch(e=>{console.error(e);process.exitCode=1;});
