const assert=require('node:assert/strict');const E=require('../underwriting.js');
const base={question:'Where should I review a diabetic client for final expense?',coverage:'final-expense',age:'65',state:'MI',diabetesType:'type2',insulin:'no',currentInsulin:'no',a1c:'7.2',diagnosisAge:'50',complications:'none',hospitalization:'no',coronary:'no'};
const guide=(type,extra={})=>({id:type,carrier:'Test',active:true,kind:'underwriting',coverage_types:['final-expense'],page_count:50,rules:{type,pages:[5]},...extra});
const core=guide('corebridge-siwl-diabetes'),ta=guide('transamerica-fe-diabetes',{carrier:'Transamerica'});
const review=(g,f)=>E.ruleReview(g,{...base,...f});
assert.match(review(core,{}).notes.join(' '),/align with the Level row only/);
assert.match(review(core,{currentInsulin:'yes'}).notes.join(' '),/Graded with insulin/);
assert.doesNotMatch(review(core,{currentInsulin:'unknown'}).notes.join(' '),/align with the Level row/);
assert.match(review(core,{a1c:'9.9'}).notes.join(' '),/8.7–9.9/);
assert.equal(review(core,{a1c:'10'}).caution,true);
assert.equal(review(core,{hospitalization:'yes'}).label,'Decline criteria flagged');
assert.equal(review(core,{coronary:'yes'}).caution,true);
assert.equal(review(core,{complications:'amputation'}).caution,true);
assert.match(review(core,{a1c:'8.65'}).notes.join(' '),/between printed thresholds/);
assert.equal(review(core,{age:'49'}).caution,true);
assert.equal(review(core,{age:'81'}).caution,true);
assert.equal(review(ta,{state:'CA'}).caution,true);
assert.match(review(ta,{diagnosisAge:'40'}).notes.join(' '),/exactly age 40/);
assert.match(review(ta,{}).notes.join(' '),/not an overall approval/);
assert.equal(E.missing(base,true).length,0);
assert.ok(E.missing({coverage:'final-expense'},true).length>=9);
let r=E.compare([core,ta,guide('other',{kind:'rates'}),guide('other',{active:false})],[],base);
assert.equal(r.candidates.length,2);assert.ok(r.primary);assert.equal(r.alternatives.length,1);
assert.equal(E.compare([core],[],{...base,coverage:'term'}).candidates.length,0);
assert.equal(E.compare([core],[],{...base,question:'Client is not diabetic but has COPD'}).candidates.length,0);
assert.equal(E.compare([core],[],{...base,question:'Diabetic with COPD'}).candidates.length,0);
assert.equal(E.compare([core],[],{...base,diabetesType:'gestational'}).candidates.length,0);
assert.equal(E.compare([core],[],{...base,diabetesType:'prediabetes'}).candidates.length,0);
assert.ok(E.searchQuery(E.terms('emphysema')).includes('COPD'));
assert.ok(E.terms('Ozempic for weight loss').includes('ozempic'));
assert.equal(E.snippet('diabetes '+Array(100).fill('x').join(' '),['diabetes']).split(/\s+/).length,12);
const hit={guide_id:core.id,page_number:5,body:'Diabetes A1C criterion',score:.4};
assert.equal(E.compare([core],[hit],{...base,question:'A1C with kidney disease'}).candidates[0].label,'Relevant guide sections');
assert.equal(E.compare([guide('instabrain-term-diabetes',{coverage_types:['term']})],[],{...base,coverage:'term',diabetesType:'type1'}).candidates[0].caution,true);
assert.deepEqual(E.pageRanges('4-12, 25',30),[{from:4,to:12},{from:25,to:25}]);
assert.throws(()=>E.pageRanges('4-40',30));
assert.throws(()=>E.pageRanges('abc',30));
console.log('34 underwriting checks passed: source scope, boundaries, missing details, exclusions, multi-condition safety, and citations.');
