const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '../..');
const target = path.join(root, 'desktop/ui');
fs.mkdirSync(path.join(target, 'vendor'), { recursive: true });
const cdn = 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';
let html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
if (html.split(cdn).length !== 2) throw new Error('Review changed frontend dependencies before packaging');
html = html.replace(cdn, '/vendor/supabase.js');
if (/<script[^>]+src=["']https?:/i.test(html)) throw new Error('Remote executable dependency detected');
const scriptHashes = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(match => "'sha256-" + crypto.createHash('sha256').update(match[1]).digest('base64') + "'");
const csp = ["default-src 'none'", "script-src 'self' " + scriptHashes.join(' '), "script-src-attr 'none'", "style-src 'self' 'unsafe-inline'", "img-src 'self' data: blob:", "connect-src https://yfuuigykpihoetgaefmu.supabase.co wss://yfuuigykpihoetgaefmu.supabase.co", "font-src 'self'", "object-src 'none'", "base-uri 'none'", "form-action 'none'", "frame-ancestors 'none'"].join('; ');
fs.writeFileSync(path.join(target, 'index.html'), html);
for (const file of ['team-leaders.js', 'corporate-blue.css', 'dashboard.js', 'dashboard.css']) fs.copyFileSync(path.join(root, file), path.join(target, file));
const pkgRoot = path.join(root, 'desktop/node_modules/@supabase/supabase-js');
fs.copyFileSync(path.join(pkgRoot, 'dist/umd/supabase.js'), path.join(target, 'vendor/supabase.js'));
fs.mkdirSync(path.join(target, 'assets'), { recursive: true });
fs.copyFileSync(path.join(root, 'assets/lld-icon-v1.png'), path.join(target, 'assets/lld-icon-v1.png'));
const files = ['/dashboard.js', '/dashboard.css', '/assets/lld-icon-v1.png', '/index.html', '/team-leaders.js', '/corporate-blue.css', '/vendor/supabase.js'];
const hashes = Object.fromEntries(files.map(file => [file, crypto.createHash('sha256').update(fs.readFileSync(path.join(target, file))).digest('hex')]));
fs.writeFileSync(path.join(target, 'manifest.json'), JSON.stringify({ files, csp, hashes }, null, 2));
console.log('Prepared unchanged portal UI with bundled Supabase SDK and hashed inline scripts.');
