'use strict';
const {createHmac,timingSafeEqual,randomUUID}=require('node:crypto');
const {config,failure,MASTER}=require('./dialer');
const {rpc,UUID}=require('./lead-calling');
const BASE='https://yfuuigykpihoetgaefmu.supabase.co',KEY='sb_publishable_6O3XhhYJrjhN_5U1cFxz2g_fYI-3uE6';
const PURPOSE='vivid_dialer_full_v1',ORIGIN='https://www.lldportal.com';
function mode(){const key=process.env.STRIPE_SECRET_KEY;if(!/^sk_(test|live)_[A-Za-z0-9]+$/.test(key||''))throw failure(503,'Stripe billing is not configured.');const live=key.startsWith('sk_live_');if(live&&process.env.DIALER_LIVE_BILLING_ENABLED!=='true')throw failure(503,'Live billing has not been enabled.');return live;}
async function authenticate(req){
 const auth=req.headers.authorization||'';if(!/^Bearer [A-Za-z0-9_.-]+$/.test(auth))throw failure(401,'Sign in to the portal first.');
 const headers={apikey:KEY,Authorization:auth};const r=await fetch(BASE+'/auth/v1/user',{headers,signal:AbortSignal.timeout(8000)});if(!r.ok)throw failure(401,'Your session expired. Sign in again.');const u=await r.json();
 let claims;try{claims=JSON.parse(Buffer.from(auth.slice(7).split('.')[1],'base64url'))}catch{throw failure(401,'Invalid session.');}
 if(claims.sub!==u.id||claims.exp<=Date.now()/1000||claims.aal!=='aal2'||!UUID.test(claims.session_id||''))throw failure(403,'Complete two-step verification first.');
 const p=await fetch(BASE+'/rest/v1/profiles?id=eq.'+u.id+'&select=id,role,active,archived',{headers,signal:AbortSignal.timeout(8000)});if(!p.ok)throw failure(403,'Could not verify access.');const rows=await p.json();
 if(rows.length!==1||!rows[0].active||rows[0].archived||!['admin','agent'].includes(rows[0].role))throw failure(403,'Your account is unavailable.');
 if(!await rpc('dialer_session_valid',{p_user:u.id,p_session:claims.session_id}))throw failure(401,'Your session is no longer active.');
 return {id:u.id,email:u.email,sessionId:claims.session_id,live:mode()};
}
async function database(path,body,method){const k=process.env.SUPABASE_SECRET_KEY;if(!/^sb_secret_[A-Za-z0-9_-]+$/.test(k||''))throw failure(503,'Dialer database is not configured.');const r=await fetch(BASE+'/rest/v1/'+path,{method:method||(body===undefined?'GET':'POST'),headers:{apikey:k,'Content-Type':'application/json',Prefer:'return=representation'},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(10000)});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{throw failure(502,'Invalid database response.');}if(!r.ok)throw failure(409,d?.message||'Dialer database request failed.');return d;}
async function stripe(path,body,idempotency){mode();const r=await fetch('https://api.stripe.com/v1/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+process.env.STRIPE_SECRET_KEY,...(body?{'Content-Type':'application/x-www-form-urlencoded'}:{}),...(idempotency?{'Idempotency-Key':idempotency}:{})},...(body?{body:new URLSearchParams(body).toString()}:{}),signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok)throw failure(502,'Stripe request failed. Retry or contact your administrator.');return d;}
async function twilio(path,body,method){const c=config();const r=await fetch('https://api.twilio.com/2010-04-01/Accounts/'+c.TWILIO_ACCOUNT_SID+'/'+path,{method:method||(body?'POST':'GET'),headers:{Authorization:'Basic '+Buffer.from(c.TWILIO_ACCOUNT_SID+':'+c.TWILIO_AUTH_TOKEN).toString('base64'),...(body?{'Content-Type':'application/x-www-form-urlencoded'}:{})},...(body?{body:new URLSearchParams(body).toString()}:{}),signal:AbortSignal.timeout(15000)});if(r.status===204)return null;const d=await r.json();if(!r.ok)throw failure(r.status===404?404:502,'Phone provider request failed. Retry or contact your administrator.');return d;}
const identity=id=>'vivid_'+id.replace(/-/g,'');
function signed(h,p,secret){const b=[h,p].map(v=>Buffer.from(JSON.stringify(v)).toString('base64url')).join('.');return b+'.'+createHmac('sha256',secret).update(b).digest('base64url');}
function callTokens(u,id,c){const t=Math.floor(Date.now()/1000),who=identity(u.id);return {token:signed({alg:'HS256',typ:'JWT',cty:'twilio-fpa;v=1'},{jti:c.TWILIO_API_KEY_SID+'-'+randomUUID(),iss:c.TWILIO_API_KEY_SID,sub:c.TWILIO_ACCOUNT_SID,iat:t,nbf:t-5,exp:t+300,grants:{identity:who,voice:{outgoing:{application_sid:c.TWILIO_TWIML_APP_SID},incoming:{allow:false}}}},c.TWILIO_API_KEY_SECRET),callGrant:signed({alg:'HS256',typ:'JWT'},{aud:PURPOSE,sub:u.id,callId:id,exp:t+60},c.TWILIO_API_KEY_SECRET)};}
function grant(token,c){if(typeof token!=='string'||token.length>2048)throw failure(403,'Invalid authorization.');const parts=token.split('.');if(parts.length!==3)throw failure(403,'Invalid authorization.');const a=createHmac('sha256',c.TWILIO_API_KEY_SECRET).update(parts.slice(0,2).join('.')).digest(),b=Buffer.from(parts[2],'base64url');if(a.length!==b.length||!timingSafeEqual(a,b))throw failure(403,'Invalid authorization.');let h,p;try{h=JSON.parse(Buffer.from(parts[0],'base64url'));p=JSON.parse(Buffer.from(parts[1],'base64url'));}catch{throw failure(403,'Invalid authorization.');}const t=Date.now()/1000;if(h.alg!=='HS256'||h.typ!=='JWT'||p.aud!==PURPOSE||!UUID.test(p.sub||'')||!UUID.test(p.callId||'')||!Number.isInteger(p.exp)||p.exp<=t||p.exp>t+90)throw failure(403,'Authorization expired.');return p;}
function callbackValid(req,b,c,path){if(req.url!==path||!b||Array.isArray(b))return false;let raw=ORIGIN+path;for(const k of Object.keys(b).sort()){if(typeof b[k]!=='string')return false;raw+=k+b[k];}const a=Buffer.from(createHmac('sha1',c.TWILIO_AUTH_TOKEN).update(raw).digest('base64')),v=Buffer.from(req.headers['x-twilio-signature']||'');return a.length===v.length&&timingSafeEqual(a,v);}
function endpoint(fn){return async(req,res)=>{res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Use POST.'});if(req.headers.origin!==ORIGIN)return res.status(403).json({error:'Open the dialer from the portal.'});try{if(!req.body||typeof req.body!=='object'||Array.isArray(req.body))throw failure(400,'Invalid request.');return res.status(200).json(await fn(req,await authenticate(req)));}catch(e){return res.status(e.status||503).json({error:e.status?e.message:'Dialer temporarily unavailable. Please retry.'});}};}
module.exports={authenticate,mode,database,stripe,twilio,identity,callTokens,grant,callbackValid,endpoint,config,failure,rpc,UUID,PURPOSE,ORIGIN,MASTER};
