'use strict';
const {createHmac,timingSafeEqual}=require('node:crypto');
const {MASTER,IDENTITY,failure,tokens}=require('./dialer');
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
async function rpc(name,body){const key=process.env.SUPABASE_SECRET_KEY;if(!/^sb_secret_[A-Za-z0-9_-]+$/.test(key||''))throw failure(503,'Calling requires the Supabase server key.');const r=await fetch('https://yfuuigykpihoetgaefmu.supabase.co/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(10000)});const d=await r.json();if(!r.ok)throw failure(409,d.message||'This lead cannot be called.');return d;}
function authorization(c,leadId,callId,to){const t=Math.floor(Date.now()/1000),header=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url'),payload=Buffer.from(JSON.stringify({aud:'vivid-master-lead-call',sub:MASTER,identity:IDENTITY,leadId,callId,to,callerId:c.TWILIO_PHONE_NUMBER,exp:t+60})).toString('base64url'),body=header+'.'+payload;return {...tokens(c),callGrant:body+'.'+createHmac('sha256',c.TWILIO_API_KEY_SECRET).update(body).digest('base64url'),destination:to,leadId};}
function verify(token,c){if(typeof token!=='string'||token.length>2048)throw failure(403,'Invalid lead call authorization.');const parts=token.split('.');if(parts.length!==3)throw failure(403,'Invalid lead call authorization.');const sig=createHmac('sha256',c.TWILIO_API_KEY_SECRET).update(parts[0]+'.'+parts[1]).digest(),given=Buffer.from(parts[2],'base64url');if(given.length!==sig.length||!timingSafeEqual(given,sig))throw failure(403,'Invalid lead call authorization.');let h,p;try{h=JSON.parse(Buffer.from(parts[0],'base64url'));p=JSON.parse(Buffer.from(parts[1],'base64url'))}catch{throw failure(403,'Invalid lead call authorization.')}const now=Math.floor(Date.now()/1000);if(h.alg!=='HS256'||h.typ!=='JWT'||p.aud!=='vivid-master-lead-call'||p.sub!==MASTER||p.identity!==IDENTITY||!UUID.test(p.leadId||'')||!UUID.test(p.callId||'')||!/^\+1[2-9]\d{2}[2-9]\d{6}$/.test(p.to||'')||(p.callerId!==undefined&&!/^\+1[2-9]\d{2}[2-9]\d{6}$/.test(p.callerId))||!Number.isInteger(p.exp)||p.exp<=now||p.exp>now+90)throw failure(403,'Expired or invalid lead call authorization.');return p;}
function array(v){if(Array.isArray(v))return v;try{const a=JSON.parse(v);return Array.isArray(a)?a:[]}catch{return []}}
function displayLead(l){const headers=array(l.csv_headers),values=array(l.csv_values);function field(names){const matches=headers.map((h,i)=>names.includes(String(h).toLowerCase().replace(/[^a-z0-9]/g,''))?i:-1).filter(i=>i>=0);return matches.length===1?String(values[matches[0]]||''):''}return {...l,first_name:l.first_name||field(['firstname','name','fullname','clientname']),last_name:l.last_name||field(['lastname']),phone:l.phone||field(['phone','phonenumber','mobile','mobilephone','cell','cellphone','telephone']),email:l.email||field(['email','emailaddress']),state:l.state||field(['state']),csv_headers:undefined,csv_values:undefined};}
module.exports={rpc,authorization,verify,displayLead,UUID};
