'use strict';
const {randomUUID}=require('node:crypto');
const legacy=require('./docusign');
const {failure}=require('./dialer-full');
const {UUID}=require('./lead-calling');
const {database,storage,allRows,onboardingProgress,MASTER}=legacy;
const TABLE='portal_signwell_agreements',BASE='https://yfuuigykpihoetgaefmu.supabase.co';
function enabled(){return !!process.env.SIGNWELL_API_KEY&&!!process.env.SIGNWELL_TEMPLATE_ID;}
function environment(){return process.env.SIGNWELL_LIVE_SIGNING_ENABLED==='true'?'live':'demo';}
function master(u){if(!u.master)throw failure(403,'Only the Master account can manage signing setup.');}
async function sw(path,body,binary=false){if(!enabled())throw failure(503,'SignWell is not configured.');const r=await fetch('https://www.signwell.com/api/v1/'+path,{method:body?'POST':'GET',headers:{'X-Api-Key':process.env.SIGNWELL_API_KEY,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(25000)});if(!r.ok){let errors;try{errors=(await r.json()).errors;}catch{}const fields=errors&&typeof errors==='object'?Object.keys(errors).filter(k=>['recipients','template_id','template_id_or_ids','metadata','subject','message','api_application_id','test_mode'].includes(k)):[];console.error('signwell_request_failed',{status:r.status,fields});const e=failure(502,errors?.recipients?.duplicated_emails?'SignWell requires different emails for the Agent and Agency signer.':r.status===422?'SignWell rejected the agreement details. Please contact your administrator.':'SignWell request failed. Check the API key, template and API allowance.');e.providerValidationRejected=r.status===422;throw e;}return binary?Buffer.from(await r.arrayBuffer()):r.json();}
function validateTemplate(t){const p=t.placeholders||[],agent=p.filter(r=>r.name==='Agent'),agency=p.filter(r=>r.name==='Agency');if(p.length!==2||agent.length!==1||agency.length!==1)throw failure(400,'SignWell returned these placeholders: '+p.map(r=>String(r.name||'(unnamed)').slice(0,80)).join(', ')+'. Use exactly Agent and Agency, then save the template.');if(t.apply_signing_order!==true)throw failure(400,'SignWell reports Apply sending order is OFF. Turn it ON and click Save Template.');for(const name of ['Agent','Agency'])if(!(t.fields||[]).flat().some(f=>f.placeholder_name===name&&String(f.type).toLowerCase()==='signature'&&f.required===true&&!f.value))throw failure(400,name+' needs an unsigned required signature field in the saved template.');return t;}
async function template(){if(!UUID.test(process.env.SIGNWELL_TEMPLATE_ID||''))throw failure(503,'Invalid SignWell template ID.');return validateTemplate(await sw('document_templates/'+process.env.SIGNWELL_TEMPLATE_ID));}
async function agreement(u){return (await database(TABLE+'?user_id=eq.'+u.id+'&environment=eq.'+environment()+'&superseded=eq.false&limit=1'))?.[0]||null;}
function publicAgreement(a){return a?{id:a.id,status:a.status,waiting_on:a.waiting_on,envelope_id:a.document_id,signing_method:'email',pdf_path:a.pdf_path,certificate_path:null,provider:'SignWell'}:null;}
function documentStatus(d){const s=String(d.status||'').toLowerCase();const status={created:'sent',sent:'sent',viewed:'delivered',pending:'signed',completed:'completed',declined:'declined',expired:'voided',cancelled:'voided',canceled:'voided'}[s];if(!status)throw failure(502,'Unexpected SignWell document status.');const rs=d.recipients||[],a=rs.find(r=>r.placeholder_name==='Agent'||String(r.id)==='1'),b=rs.find(r=>r.placeholder_name==='Agency'||String(r.id)==='2');const done=r=>['completed','signed'].includes(String(r?.status||'').toLowerCase());return {status,waiting_on:['completed','declined','voided'].includes(status)?null:!done(a)?'agent':!done(b)?'agency':null};}
async function refresh(u,record){const a=record||await agreement(u);if(!a?.document_id)return a;const d=await sw('documents/'+a.document_id);if(d.id!==a.document_id||d.test_mode!==(a.environment==='demo'))throw failure(409,'Document environment could not be verified.');const patch=documentStatus(d);if(a.status==='completed'&&patch.status!=='completed')throw failure(409,'Completed signing status could not be verified.');if(patch.status==='completed'){if(!(d.recipients||[]).length||!(d.recipients||[]).every(r=>['completed','signed'].includes(String(r.status).toLowerCase())))throw failure(502,'Both signatures must be complete.');patch.completed_at=a.completed_at||new Date().toISOString();}await database(TABLE+'?id=eq.'+a.id,{...patch,checked_at:new Date().toISOString()},'PATCH');Object.assign(a,patch);if(a.status==='completed'&&!a.pdf_path){const pdf=await sw('documents/'+a.document_id+'/completed_pdf?url_only=false&audit_page=true&file_format=pdf',undefined,true);if(pdf.length>20000000||pdf.subarray(0,5).toString()!=='%PDF-')throw failure(502,'Invalid signed PDF.');const path=a.user_id+'/signwell/'+a.environment+'/'+a.id+'/agreement-with-audit.pdf';await storage('object/onboarding-agreements/'+path,{method:'POST',headers:{'Content-Type':'application/pdf','x-upsert':'true'},body:pdf});await database(TABLE+'?id=eq.'+a.id,{pdf_path:path},'PATCH');a.pdf_path=path;}return a;}
async function status(u){let a=await agreement(u);if(a?.document_id){try{a=await refresh(u,a);}catch(e){console.error('signwell_status_refresh_failed',{status:e.status||503});}}const resources=await database('portal_onboarding_resources?user_id=eq.'+u.id);return {provider:'SignWell',environment:environment(),connected:enabled(),signingReady:enabled()&&(environment()==='live'||u.master),agreement:publicAgreement(a),resources:resources?.[0]||{}};}
async function sign(u,b={}){if(environment()==='demo')master(u);let a=await agreement(u);if(a&&!a.document_id)throw failure(409,'Creation needs administrator review. Do not create a duplicate.');if(a){a=await refresh(u,a);if(['completed','declined','voided'].includes(a.status))throw failure(409,'This agreement cannot be signed again.');return {delivery:'email',email:a.signer_email};}await template();if(!u.full_name||!u.email)throw failure(400,'A name and email are required.');const peter=(await database('profiles?id=eq.'+MASTER+'&select=full_name,email,active,archived,is_super_admin'))?.[0];if(!peter?.active||peter.archived||!peter.is_super_admin||!peter.email)throw failure(503,'Agency signer is unavailable.');const requestedEmail=b.email??(environment()==='demo'&&u.master?b.testEmail:undefined);if(requestedEmail!==undefined&&typeof requestedEmail!=='string')throw failure(400,'Enter a valid email for your agreement.');const signerEmail=(requestedEmail===undefined?u.email:requestedEmail).trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(signerEmail)||signerEmail.length>254)throw failure(400,'Enter a valid email for your agreement.');if(signerEmail.toLowerCase()===peter.email.trim().toLowerCase())throw failure(400,'SignWell requires different emails for Agent and Agency. Enter another email you control in Best email for your agreement.');const id=randomUUID();await database(TABLE,{id,user_id:u.id,environment:environment(),template_id:process.env.SIGNWELL_TEMPLATE_ID,status:'creating',signer_name:u.full_name,signer_email:signerEmail});let d;try{d=await sw('document_templates/documents',{template_id:process.env.SIGNWELL_TEMPLATE_ID,test_mode:environment()==='demo',draft:false,embedded_signing:false,apply_signing_order:true,allow_reassign:false,name:'Vivid Life Agent NDA and Chargeback Agreement',subject:'Vivid Life — Agent NDA and Chargeback Agreement',metadata:{portal_agreement_id:id},recipients:[{id:'1',placeholder_name:'Agent',name:u.full_name,email:signerEmail,delivery_method:'email'},{id:'2',placeholder_name:'Agency',name:peter.full_name,email:peter.email,delivery_method:'email'}]});}catch(e){if(e.providerValidationRejected)await database(TABLE+'?id=eq.'+id+'&user_id=eq.'+u.id+'&status=eq.creating&document_id=is.null',undefined,'DELETE');throw e;}if(!UUID.test(d.id||''))throw failure(502,'Unable to confirm creation. Contact your administrator.');await database(TABLE+'?id=eq.'+id,{document_id:d.id,status:'sent',waiting_on:'agent'},'PATCH');return {delivery:'email',email:signerEmail};}
async function overview(u){master(u);const [profiles,checks,receipts,resources,agreements,agencies]=await Promise.all([allRows('profiles?active=eq.true&archived=eq.false&role=in.(agent,admin)&select=id,full_name,email,division,role&order=full_name.asc,id.asc'),allRows('portal_onboarding_checklists?select=user_id,welcome_read_at,compliance_acknowledged_at,npn,licensed_states&order=user_id.asc'),allRows('portal_onboarding_receipts?completion_kind=eq.acknowledged&select=user_id,completion_kind&order=user_id.asc'),allRows('portal_onboarding_resources?select=user_id,xcel,study,exam&order=user_id.asc'),allRows(TABLE+'?environment=eq.'+environment()+'&superseded=eq.false&order=user_id.asc'),allRows('divisions?select=id,name&order=id.asc')]);const map=rows=>new Map(rows.map(r=>[r.user_id,r])),cm=map(checks),rm=map(receipts),xm=map(resources),am=map(agreements),names=new Map(agencies.map(a=>[a.id,a.name]));return {environment:environment(),rows:profiles.filter(p=>p.id!==MASTER).map(p=>onboardingProgress({...p,division:names.get(p.division)||p.division||'Unassigned'},cm.get(p.id),rm.get(p.id),xm.get(p.id),publicAgreement(am.get(p.id))))};}
async function action(req,res,u){const b=req.body||{};switch(b.action){case 'status':return status(u);case 'overview':return overview(u);case 'sign':return sign(u,b);case 'refresh':return {agreement:publicAgreement(await refresh(u))};case 'templates':master(u);{const t=await template();return {templates:[{templateId:t.id,name:t.name}]};}case 'template':master(u);if(b.confirmed!==true||b.id!==process.env.SIGNWELL_TEMPLATE_ID)throw failure(400,'Review and confirm the configured template.');await template();return {ok:true};case 'newTest':master(u);{const a=await agreement(u);if(environment()!=='demo'||b.confirmed!==true||a?.id!==b.id||a.status!=='completed'||!a.pdf_path)throw failure(409,'Complete and archive the current test first.');await template();await database(TABLE+'?id=eq.'+a.id+'&superseded=eq.false',{superseded:true},'PATCH');return {ok:true};}case 'agreements':master(u);{const current=await database(TABLE+'?select=id,signer_name,status,pdf_path&order=created_at.desc&limit=100');const old=await legacy.action(req,res,u);return {agreements:[...current.map(a=>({...a,provider:'SignWell'})),...old.agreements.map(a=>({...a,provider:'DocuSign'}))]};}case 'refreshAgreement':case 'download':{let a;if(b.id){master(u);if(!UUID.test(b.id||''))throw failure(400,'Invalid agreement.');a=(await database(TABLE+'?id=eq.'+b.id))?.[0];if(!a)return legacy.action(req,res,u);}else a=await agreement(u);if(b.action==='refreshAgreement')return {agreement:publicAgreement(await refresh(u,a))};if(b.kind!=='agreement'||a?.status!=='completed'||!a.pdf_path)throw failure(404,'Signed PDF is not available yet.');const r=await storage('object/sign/onboarding-agreements/'+a.pdf_path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expiresIn:60})});const d=await r.json(),path=d.signedURL||d.signedUrl;if(typeof path!=='string'||!path.startsWith('/object/sign/'))throw failure(502,'Invalid download URL.');return {url:BASE+'/storage/v1'+path};}case 'resource':return legacy.action(req,res,u);default:throw failure(400,'Unknown signing action.');}}
async function reconcile(){const rows=await database(TABLE+'?document_id=not.is.null&or=(status.in.(sent,delivered,signed),and(status.eq.completed,pdf_path.is.null))&order=checked_at.asc.nullsfirst&limit=10');let checked=0,failed=0;for(const a of rows){try{await refresh({id:a.user_id},a);checked++;}catch{failed++;}}return {checked,failed};}
module.exports={enabled,environment,action,reconcile,validateTemplate,documentStatus};
